### ISSUE TITLE
subscribeEndpoint CORS error when using Access-Control-Allow-Origin *

### ISSUE THREAD

**Issue by f1nality** [centrifugal/centrifuge-js#110]
Because of withCredentials option when making subscribeEndpoint request there is error:

> Access to XMLHttpRequest at 'https://BACKEND_DOMAIN/api/centrifugo/auth/' from origin 'https://FRONTEND_DOMAIN' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

Is withCredentials needed? I can't change Access-Control-Allow-Origin * from wildcard because my service need to work with any domains (user can connect to their custom domains)

Removing
xhr.withCredentials = true;
Seems to fix the problem

**Comment by FZambia** [comment]
@f1nality hello. But if you disable `withCredentials ` you won't get cookies with request. How you will decide then whether user is allowed to subscribe on private channel or not?

**Comment by FZambia** [comment]
Closing as no response from op
