### ISSUE TITLE
RawGit has reached the end of its useful life

### ISSUE THREAD

**Issue by applecat** [centrifugal/centrifuge-js#113]
There is a link to CDN in documentation that uses RawGit:
```
<script src="//cdn.rawgit.com/centrifugal/centrifuge-js/2.X.X/dist/centrifuge.min.js"></script>
```

But RawGit [site](https://rawgit.com/) said:

> RawGit has reached the end of its useful life

Perhaps a link to jsDelivr would be better choice?
```
https://cdn.jsdelivr.net/gh/centrifugal/centrifuge-js@2.X.X/dist/centrifuge.min.js
```

**Comment by FZambia** [comment]
@applecat thanks! I fixed links in readme - but I'll try to also look for them throughout other repositories and Centrifugo docs
