### ISSUE TITLE
onPrivateSubscribe callback hasOwnProperty issue - subscribe never called

### ISSUE THREAD

**Issue by vare4ka** [centrifugal/centrifuge-js#116]
In onPrivateSubscribe callback function (key: 'stopSubscribeBatching') for_in loop doesn't work  - for (var i in channels) - as "i" is always undefined and checking channels.hasOwnProperty(i) returns false so subscribe method never called
https://github.com/centrifugal/centrifuge-js/blob/fd8c39e20a18aaef519a02d675a942f553ee4ca0/dist/centrifuge.js#L1906

**Comment by FZambia** [comment]
@vare4ka hi, could you explain a bit better? Maybe with code example.

Since if subscribe never called private subscriptions would not work at all. I have a test stand where private subscriptions work fine with latest centrifuge-js.

**Comment by vare4ka** [comment]
In my case private subscriptions don't work indeed. The context is following. On our backend they don't have "/centrifuge/subscribe" endpoint, so I wanted to use onPrivateSubscribe method. I configure it as following:
`centrifuge.current = new Centrifuge(url, {
      sockjs: SockJS,
      onPrivateSubscribe: (resp, callback) => {
        callback({
           data: {
              channels: [
                 {
                    channel: "$chan1",
                    token: "sometoken",
                 }
              ]
            },
            status: 200
        })
      }
    })`
When I debug I see that when callback is called, it goes to "stopSubscribeBatching" method and there in For_in loop it doesn't go further to subscribe as "i" is undefined and next check "if (channels.hasOwnProperty(i))" returns false, so Subscribe method isn't called there. I attached source code line number  where it happens in my first message

**Comment by FZambia** [comment]
Just tried to reproduce with code like this:

```javascript
var channel = "$chan1";

var centrifuge = new Centrifuge(address, {
    debug: true,
    onPrivateSubscribe: function(ctx, callback) {
        callback({ data: { channels: [ { channel: "$chan1", token: "sometoken", } ] }, status: 200 })
    }
});

centrifuge.setToken('my-token');

var sub = centrifuge.subscribe(channel, handleMessage)
        .on("join", handleJoin)
        .on("leave", handleLeave)
        .on("unsubscribe", handleUnsubscribe)
        .on("subscribe", handleSubscribe)
        .on("error", handleSubscribeError);

centrifuge.connect();
```

Everything works as expected: `handleSubscribeError` called. Also looking at dev tools websocket frames I can see that subscription request to private channel sent to Centrifugo with token set in `onPrivateSubscribe`, and `permission denied` received in response:

<img width="1440" alt="Screenshot 2020-07-25 at 12 38 26" src="https://user-images.githubusercontent.com/1196565/88453924-2b86bc80-ce74-11ea-8a2a-3955b5eb3bd3.png">

**Comment by FZambia** [comment]
Closing since can't reproduce and no response from op for a long time.
