### ISSUE TITLE
RPC proxy

### ISSUE THREAD

**Issue by Tsmar** [centrifugal/centrifuge-js#123]
Hi! 
https://centrifugal.github.io/centrifugo/server/proxy/#rpc-proxy
request do not transfer "data" from client to backend after call centrifuge.named RPC("method Name", {"any": "client data"}) app backend receive request without "data":
{
client: "2df604ec-efe0-4af0-b29e-a16bad3c18dd"
encoding: "json"
method: "methodName"
protocol: "protobuf"
transport: "websocket"
user: "1"
}

**Comment by FZambia** [comment]
Hello, just tried to reproduce with the latest Centrifugo server - it works fine. I called:
```
centrifuge.namedRPC("method Name", {"any": "client data"});
``` 
and received the following data on backend:
```
[I 201121 22:26:01 main:189] b'{"client":"4e4a9ca6-7fa7-4e83-83a8-8693b05fc522","transport":"websocket","protocol":"json","encoding":"json","user":"2694","method":"method Name","data":{"any":"client data"}}'
```

**Comment by Tsmar** [comment]
On backend (node):
function process(req, res, next) {
	res.json({
		result: {
			data: {
				request: req.body
			}
		}
	}).end();

result.data.request not include data (
and internal _call method receive method name and data correctly

**Comment by Tsmar** [comment]
subscribe rpc proxy working correctly

**Comment by FZambia** [comment]
Ah, I noticed you are using Protobuf. In this case to send JSON data over Protobuf connection you have to do the following:
```
var data = new TextEncoder("utf-8").encode(JSON.stringify({"any": "client data"})); 
centrifuge.namedRPC("method Name", data);
```
Could you try this?

**Comment by Tsmar** [comment]
Nice! All works, thanks!

**Comment by FZambia** [comment]
Welcome, I suppose this should be better reflected in docs - since this is not obvious at all – will try to improve soon.
