### ISSUE TITLE
[Question] Wildcard subscription on channels

### ISSUE THREAD

**Issue by mikrafizik** [centrifugal/centrifuge-js#127]
How could i listen multiple channels using wildcard the same way as I do via websockets
`topic.*.subdivision.*`

is there any tool in your library to allow client listen to multiple channels?

**Comment by FZambia** [comment]
Hello, it's possible to subscribe to multiple channels and subscriptions will be multiplexed over a single connection - just call `subscribe` many times. But wildcard subscriptions with `*` not supported and there are no plans to add them.

**Comment by mikrafizik** [comment]
Hello @FZambia. Subscribe many times is ok for 10-15 channels, but what be in case if i have 1000 channels?
or maybe  i could connect via native websocket? is it possible?

**Comment by mikrafizik** [comment]
For those who want to use  subscription via wildcard, there is a "solution". You can use `broadcast` method  to duplicate you message to topics with `*`
