### ISSUE TITLE
Application chat questions

### ISSUE THREAD

**Issue by prybus** [centrifugal/centrifuge-js#132]
Hello, I have a few questions about centrifuge. 
I want build application with chat. Everyone can create new room and invite own people. How do it on technical in centrifuge.  Room is a chanel? What i need authentication visitors user? JWT with special data is ok? 

Best regards,
Paul

**Comment by FZambia** [comment]
@prybus hello, try asking general question like this [in community rooms](https://centrifugal.github.io/centrifugo/getting_started/#join-community).

It's definitely possible to build chat app on top of Centrifuge/Centrifugo.

If you'll have many rooms on one application screen then you should not use separate channel per chat room - this does not scale well as soon as number of rooms grow. Use one personal user channel.

Other questions are not clear for me - but again, those are better suited for community chat rooms, not issue tracker.
