### ISSUE TITLE
Beginner use centrifuge  in vuejs，publish error ：103, permission denied

### ISSUE THREAD

**Issue by zkbqhuang** [centrifugal/centrifuge-js#134]
this.centrifuge.publish('channel', {'input': this.new_message}).then(function (res) {
        console.log('successfully published')
      }, function (err) {
        console.log('publish error', err)
      })

**Comment by zkbqhuang** [comment]
OUTPUT:

2021-02-23 10:43:37 [INF] client command error error="103: permission denied" client=836c92c1-7d76-485f-985c-9fd35f4f4ee5 command="id:22 method:PUBLISH params:\"{\\\"channel\\\":\\\"channel\\\",\\\"data\\\":{\\\"input\\\":\\\"2222\\\"}}\" " reply="id:22 error:<code:103 message:\"permission denied\" > " user=123722

**Comment by FZambia** [comment]
For history: https://centrifugal.github.io/centrifugo/server/channels/#publish

It's possible to publish from a client side only if option `publish` is set to `true` for channel namespace or on top level. Though usually you need to first validate data that is going to be published - so send message to backend over AJAX ( then publish to Centrifugo API from a backend), or using RPC Centrifugo proxy (then publish to Centrifugo API from a backend) or at least validate using Publish proxy.

**Comment by shokhaa** [comment]
I have almost the same error too!

**Comment by shokhaa** [comment]
with the method presence wash it off too
