### ISSUE TITLE
pbf.js

### ISSUE THREAD

**Issue by leeoniya** [centrifugal/centrifuge-js#137]
faster, smaller: https://github.com/mapbox/pbf

cc @FZambia :)

**Comment by FZambia** [comment]
Thanks - the library seems very good. But, some reasons I don't want to migrate:
* quite a lot of refactoring for no real reason
* last release of pbf was in 2019 - this is a problem for me since I am trying to rely on a well-supported third-party libraries to reduce possible risk if sth goes wrong
