### ISSUE TITLE
User Agent header improvement

### ISSUE THREAD

**Issue by vindemasi** [centrifugal/centrifuge-js#143]
Hello @FZambia ,

albeit it's possible to configure the headers creating Centrifugo object, there isn't a way to configure the websocket object. 
I would like to set the User-Agent during client/server handshake. The needed code it's very trivial. I can provide a PR for that but in my opinion, as it's an API change it's better to have your opinion (anyway  it can be done without breaking changes).

On alternative, in the case it seems to be out of the scope, is so simple to extends the Websocket class and a PR with few documentations lines can be enough. 

Cheers.

**Comment by vindemasi** [comment]
Sorry for the noise,

closed because I missed already written documentation.

**Comment by FZambia** [comment]
@vindemasi hello, take a look at `setConnectData` method of client - this may be a simpler alternative.
