### ISSUE TITLE
Constantly disconnects for every 10 to 12 secs after publish from server side.

### ISSUE THREAD

**Issue by p000ic** [centrifugal/centrifuge-js#144]
I'm using the plugin in my vue project and the connection Disconnects and Connects back every time when there is a publish message on a topic. And some times in a frequent intervals. I'm running the solution on an ubuntu 18.04 machine.

**Comment by FZambia** [comment]
Hello, please provide a reproducing example. This can be caused by many reasons.

**Comment by FZambia** [comment]
Feel free to reopen with more information and steps to reproduce. Unfortunately it's not actionable at all in this form.

**Comment by p000ic** [comment]
@FZambia  - the golang server with centrifuge was using 0.14.2 and It was updated unknowingly to 0.17.* when we had go.mod.
This was causing the issue. 
The version [0.14.2](https://pkg.go.dev/github.com/centrifugal/centrifuge@v0.14.2) is pretty stable.

Thanks.

**Comment by FZambia** [comment]
@p000ic hi, this doesn't help a lot, we are using 0.17.* in production without any problem - so this may be very specific thing which requires an example that reproduces a problem to look at.
