### ISSUE TITLE
TypeError: __webpack_require__.g.ActiveXObject is not a constructor

### ISSUE THREAD

**Issue by VityaSchel** [centrifugal/centrifuge-js#148]
I use centrifuge to connect to [DonationAlerts server](https://www.donationalerts.com/apidoc#introduction__centrifugo__subscribing_to_channel) and everything works fine until I get to 3rd step where Centrifuge has to send POST ajax request to DA endpoint in order to get channel subscription token.

This is my code:
```
centrifuge.subscribe('$alerts:donation_235774', function(message) {
    console.log('new message', message)
});
```

And I get error:
```
TypeError: __webpack_require__.g.ActiveXObject is not a constructor
    at Centrifuge._ajax (/fakepath/node_modules/centrifuge/dist/centrifuge.js:193:101)
    at Centrifuge.stopSubscribeBatching (/fakepath/node_modules/centrifuge/dist/centrifuge.js:2329:24)
    at Centrifuge._subscribe (/fakepath/node_modules/centrifuge/dist/centrifuge.js:1392:16)
    at Subscription.subscribe (/fakepath/node_modules/centrifuge/dist/centrifuge.js:2786:24)
    at Centrifuge.subscribe (/fakepath/node_modules/centrifuge/dist/centrifuge.js:2351:11)
    at subscribeToDonations (/fakepath/cen.js:27:14)
    at Centrifuge.<anonymous> (/fakepath/cen.js:20:3)
    at Centrifuge.emit (/fakepath/node_modules/centrifuge/dist/centrifuge.js:3089:5)
    at Centrifuge._connectResponse (/fakepath/node_modules/centrifuge/dist/centrifuge.js:1550:12)
```

Looks like it only happens when channel name starts with $ character.
I tried `alerts:donation_235774`, `news` — no errors. But as soon as I add $ before anything — it breaks. Also tried `aasd$asdas` and no errors thrown.

OS: MacOS Big Sur 11.0.1
Version of Centrifuge-js: 2.7.5
NodeJS version: v15.2.1
NPM version: 7.0.10
I use WebSockets for nodejs, also tried with sockjs and it couldn't even connect to server

**Comment by VityaSchel** [comment]
```
      var xhr = __webpack_require__.g.XMLHttpRequest ? new __webpack_require__.g.XMLHttpRequest() : new __webpack_require__.g.ActiveXObject('Microsoft.XMLHTTP');
                                                                                                    ^
```

**Comment by VityaSchel** [comment]
Is it because I use nodejs environment and there is not XMLhttprequest? Should I install polyfill? If yes, how do I use it in my code, how to define it globally so webpack can see it?

**Comment by VityaSchel** [comment]
Just checked g variable in webpack by logging it in console (in centifuge.js). There is no "ActiveXObject" at all. So it is undefined.

![image](https://user-images.githubusercontent.com/59040542/119965245-19f1d200-bfbb-11eb-8886-1db43dd7aaf5.png)

**Comment by VityaSchel** [comment]
I checked this code on my windows machine, exactly the same error: ActiveXObject is not a constructor

**Comment by VityaSchel** [comment]
I installed xmlhttprequest module globally, saved it to the package json but error isn't gone

**Comment by VityaSchel** [comment]
@FZambia Please confirm this issue and if you can reproduce it, I think best solution would be to add xmlhttprequest to dependencies of centrifuge-js module

**Comment by VityaSchel** [comment]
I added npm and nodejs versions to my issue. I'll try to upgrade them to latest stable versions and see if issue is gone

**Comment by VityaSchel** [comment]
yay I finally found a workaround! (please don't close issue)
1. Replace everything in node_modules/centrifuge/dist/centrifuge.js (starting from line 189) to
```javascript
var _this2 = this;

callback({
  data: _this2.fetchedData,
  status: 200
});
```

so you will have function like this: 

```javascript
value: function _ajax(url, params, headers, data, callback) {
  var _this2 = this;

  callback({
    data: _this2.fetchedData,
    status: 200
  });
}
```
2. Every time you want to connect to private channel you have to manually pre-fetch needed data with post ajax and set information to the Centrifugo class object
```javascript
const getChannelAndToken = async () => {
  let response = await fetch('https://www.donationalerts.com/api/v1/centrifuge/subscribe', {
    method: 'POST',
    body: JSON.stringify({
      channels: ['$alerts:donation_235774'],
      client: clientID // this is the centrifuge client uuid you got while connecting
    }),
    headers: {'Authorization': `Bearer ${access_token}`, 'Content-Type': 'application/json'}
  })
  let responseJSON = await response.json()
  return responseJSON
}
```
Pass parsed json to the class object:
`centrifuge.fetchedData = daResponse`
3. Now call subscribe method
```javascript
centrifuge.subscribe('$alerts:donation_235774', function(message) {
      console.log('new message', message)
  }).on("join", function(message) {
    console.log("Client joined channel", message);
  }).on("leave", function(message) {
    console.log("Client left channel", message);
  })
```

I don't know if it works with re-opening connections and keep them persistent but at least it works 😜

**Comment by VityaSchel** [comment]
> Hello, try to add https://www.npmjs.com/package/xmlhttprequest to dependencies of your NodeJS project and then:
> 
> ```js
> const Centrifuge = require('centrifuge');
> 
> global.WebSocket = require('ws'); 
> global.XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;
> 
> var centrifuge = new Centrifuge('ws://localhost:8000/connection/websocket')
> ```

Thanks! Works perfect

**Comment by FZambia** [comment]
Cool, looks like I need to add explicit option to pass it into Centrifuge like we have with WebSocket and write docs.
