### ISSUE TITLE
Custom connect message

### ISSUE THREAD

**Issue by liho98** [centrifugal/centrifuge-js#152]
![image](https://user-images.githubusercontent.com/44250267/124603503-90c49980-de9c-11eb-8a23-e69e39e022c2.png)

Some websocket servers do not allow messages that do not conform to their message format.

how do i customize the connect message? or should it be a feature request?

**Comment by FZambia** [comment]
Hello, centrifuge-js is not a generic WebSocket client - it's a connector for Centrifugo server (https://github.com/centrifugal/centrifugo) or for a server based on Centrifuge library for Go (https://github.com/centrifugal/centrifuge).

So you can not use it to connect to some other WebSocket server - only if that server works over the same client protocol.

**Comment by liho98** [comment]
ok got it, thanks
