### ISSUE TITLE
Ability to not set withCredentials to true

### ISSUE THREAD

**Issue by yakimka** [centrifugal/centrifuge-js#155]
I have the same problem that in https://github.com/centrifugal/centrifuge-js/issues/110 and I don't want to set `withCredentials` to `true`. I believe that this should be configured in the [configuration parameters](https://github.com/centrifugal/centrifuge-js#configuration-parameters).

>If you disable withCredentials you won't get cookies with request. Do you have an alternative way to decide whether user is allowed to subscribe on private channel or not?

I can set Authorization header with token [(example)](https://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication)

**Comment by FZambia** [comment]
@yakimka hello!

Could you send a pr with option `disableWithCredentials` (by default false - i.e. `withCredentials` is used)?

**Comment by yakimka** [comment]
Hello!
https://github.com/centrifugal/centrifuge-js/pull/156
