### ISSUE TITLE
Pass custom http header to connect

### ISSUE THREAD

**Issue by hound672** [centrifugal/centrifuge-js#157]
Hello.
Can I pass custom Http header to centrifugo connection endpoint?

Due to this https://coletiv.com/blog/using-websockets-with-cookie-based-authentication/
I want to use csrf protection.
Pass csrf token to http header which centrifugo will pass to backend endpoint
Of course this vulnerability makes sense only for cookie based auth.

**Comment by FZambia** [comment]
Browser API does not allow setting custom headers, you can only set custom headers in non-browser environment - [like this](https://github.com/centrifugal/centrifuge-js#custom-websocket-constructor). Browser automatically set Origin and Cookie for requests to the same domain.

Regarding security stuff: you can set allowed origins in Centrifugo config, and you can pass whatever data you need (like `csrf` token) using [setConnectData](https://github.com/centrifugal/centrifuge-js/blob/2.7.7/src/centrifuge.js#L120) method.

**Comment by hound672** [comment]
> Browser API does not allow setting custom headers, you can only set custom headers in non-browser environment - [like this](https://github.com/centrifugal/centrifuge-js#custom-websocket-constructor). Browsers automatically set Origin and Cookie for requests to the same domain.
> 
> Regarding security stuff: you can set allowed origins in Centrifugo config, and you can pass whatever data you need (like `csrf` token) using [setConnectData](https://github.com/centrifugal/centrifuge-js/blob/2.7.7/src/centrifuge.js#L120) method.

With this method I can add custom header which will be sent to backend (when I use proxy connection)?

**Comment by FZambia** [comment]
> With this method I can add custom header which will be sent to backend (when I use proxy connection)?

You can add any custom data (not a header), this data will be sent to your application backend inside [connect request JSON body](https://github.com/centrifugal/centrifugo/blob/v2.8.6/internal/proxy/connect_handler.go#L47). It's not documented for some reason.

**Comment by hound672** [comment]
Ok. thanks)
