### ISSUE TITLE
JWT token expired

### ISSUE THREAD

**Issue by dgastudio** [centrifugal/centrifuge-js#158]
Hello
i'm using my custom jwt token on react project. Same token, with some additional fields is used for centrifugo authorization.
My token expire in 1 hour, after this time, with help of axios interceptors is being reloaded. But is not being reloaded in centrifugo connection. So, i have to move the token to global state, and update the centrifugo connection after token has been changed.a

Is where a way, in centrifugo connection, to do token refresh if my current token has been expired?

thank you

**Comment by FZambia** [comment]
Hello @dgastudio 

centrifuge-js should automatically send a refresh request to [refreshEndpoint](https://github.com/centrifugal/centrifuge-js#refreshendpoint) when token is going to expire. Have you seen this option? Have you tried it?

**Comment by dgastudio** [comment]
Yes, I have seen it. But  as already mentioned, my system refresh jwt token by axios interceptors. I don’t need to uterus another token. Is where any callback for refresh instead of doing request?
10 авг. 2021 г., 23:04 +0300, Alexander Emelin ***@***.***>, писал:

**Comment by FZambia** [comment]
See `onRefresh` option described in README in [refreshEndpoint](https://github.com/centrifugal/centrifuge-js#refreshendpoint) section.

**Comment by dgastudio** [comment]
oh, sorry
thank you!

**Comment by FZambia** [comment]
Welcome! Feel free to reopen an issue if you won't be able to make it working for some reason.
