### ISSUE TITLE
library not working in nodejs

### ISSUE THREAD

**Issue by Adityapanther** [centrifugal/centrifuge-js#162]
have a look on that, I Imported lib and used but not working to connect

**Comment by FZambia** [comment]
Hello!

https://github.com/centrifugal/centrifuge-js#using-with-nodejs - reopen with more details if that does not work.

**Comment by Adityapanther** [comment]
So, I installed lib using npm and imported the lib on js file and trying to connect to wesocket server but not connecting to server, same code working with CDN

**Comment by FZambia** [comment]
Following instructions in readme (https://github.com/centrifugal/centrifuge-js#using-with-nodejs):

```javascript
const Centrifuge = require('centrifuge');
const WebSocket = require('ws');

var centrifuge = new Centrifuge('ws://localhost:8000/connection/websocket', {
    websocket: WebSocket
})

centrifuge.on('connect', function (ctx) {
    console.log(ctx);
})

centrifuge.connect()
```

I just checked it – and it works.
