### ISSUE TITLE
Unable to retrieve epoch from the history method

### ISSUE THREAD

**Issue by diegojancic** [centrifugal/centrifuge-js#163]
According to [the docs](https://github.com/centrifugal/centrifuge-js#history-method-of-subscription), the `history()` function should return a response that includes the `epoch` and offset.

However, in my tests the epoch is always empty and the offset always zero. Here's the code I'm using:

```javascript
var centrifuge = new Centrifuge(options.url);
centrifuge.setToken(options.token);

var callbacks = {
    "subscribe": function (context) {
        // channel: "<channel-name>"
        // isResubscribe: false        <--- Always false
        // recovered: false              <--- Always false
    }
};

const subscription = centrifuge.subscribe(channelName, callbacks);

subscription.history().then(function (response) {
    // epoch: ""        <--- Always empty
    // offset: 0        <--- Always zero
    // publications: [{...}]
}, function (err) {
    console.log(err);
});

centrifuge.connect();
```

These are the configs in centrifugo:
```json
{
  "v3_use_offset": true,
  "history_recover": true,
  "history_size": 10,
  "history_lifetime": 60,
  "token_hmac_secret_key": "<random-key>",
  "admin_password": "<random-key>",
  "admin_secret": "<random-key>",
  "api_key": "<random-key>"
}
```

I'm using Centrifugo v2.8.6 and CentrifugoJs v2.7.7.

I'm trying to recover the messages lost when the user disconnects (working) and detecting the case when "it's not possible to recover the lost messages", so I can reload all from the server. 

Am I setting it up wrong? I appreciate your help. Thank you!

**Comment by FZambia** [comment]
@diegojancic hello, for now it's only available with a server based on Centrifuge library for Go and not available in Centrifugo. There is a bold warning about this in the docs section you pointed to.

But, history operations like this will be available in Centrifugo v3 which I hope will be released shortly. Probably later today.

Sorry for the confusion, lets keep this issue open so that I wont forget to update a readme a bit later.

**Comment by FZambia** [comment]
With Centrifugo v4 all SDKs support all core features existing at the moment. Clients follow [common SDK spec](https://centrifugal.dev/docs/transports/client_api). Closing as this issue is not really actual anymore.
