### ISSUE TITLE
Batching working only for the first time

### ISSUE THREAD

**Issue by davidsa** [centrifugal/centrifuge-js#167]
Hi,

I'm trying to batch some private subscriptions, and I'm having trouble with subsequence calls to `startBatching` and `stopBatching`.

Any idea on what I might be doing wrong?

Thank you in advance!

**Comment by FZambia** [comment]
Hello, please post an example that reproduces what you mean. Self-contained, without any dependencies like React. And steps to reproduce.

**Comment by FZambia** [comment]
Closing since no response from op for a long time
