### ISSUE TITLE
Non-Error promise rejection

### ISSUE THREAD

**Issue by Ivan-Baranov** [centrifugal/centrifuge-js#170]
UnhandledRejection
Non-Error promise rejection captured with keys: code, message

After long sleep fire disconnect event, and then after 4...30 sec fire UnhandledRejection.

See: _createErrorObject
Version: 2.6.4
Reported by Sentry

**Comment by FZambia** [comment]
@Ivan-Baranov hello, thanks. Any chance for a more detailed steps to reproduce?

**Comment by FZambia** [comment]
Closing, please reopen if reproduces on recent versions of SDK.
