### ISSUE TITLE
Set onRefresh not in constructor

### ISSUE THREAD

**Issue by dgastudio** [centrifugal/centrifuge-js#177]
Hey

is it possible to set onRefresh not in the constructor?

i need this because i want to reuse the ws client for multiple components so don't want to re-initialize it every time

**Comment by FZambia** [comment]
@dgastudio hello, please provide examples of desired API. I don't understand what you mean.

**Comment by dgastudio** [comment]
Basically, I need to reuse the ws client between multiple components

Example
application.jsx
include the  "new Centrifuge(ws_url, {...}), to use it for the whole project

chat.jsx
include already defined centrifugo client, and use  centrifuge.publish on it

but, also, my project is based on JWT token auth, which one can be refreshed by centrifugo or by AXIOS. So the token is stored in global state and shared across all the components. So, if centrifugo updates jwt, it will be also updated for axios.

So, i would like to have something like axios interceptors

example https://pastebin.com/iLhyfLfv

this code, configures the global instance of Axios for any feature usage.

**Comment by FZambia** [comment]
It seems I now understand what you currently have. But I don't understand  what's wrong with the current approach and what you are suggesting/asking.

**Comment by dgastudio** [comment]
Please, take a look

https://pastebin.com/ruxM9WLc

app.jsx
include and run centrifugeConfigure ( will set all the required settings)

chat.jsx
include and run centrifugePublish (will do a publish for already configured client)

**Comment by FZambia** [comment]
Since `onRefresh` is a function you can already change its behavior at any moment in a way you need. Also, I don't understand why Centrifuge instance initialization can't depend on existing token infrastructure. Some options are required for issuing connect request to the server - so adding a method to set all options later after initialization seems error-prone.
