### ISSUE TITLE
Connecting error "Invalid message"

### ISSUE THREAD

**Issue by nikis** [centrifugal/centrifuge-js#18]
I use Centrifugo version: 1.5.1 and centrifuge-js lastes version. When trying to connect always got disconnect event with error "Invalid message". The problem that i found is in ._send(). In versions before 1.3 each message is encode and send separately, in versions after 1.3 all messages are send at once.

**Comment by FZambia** [comment]
Hello! It's normal behaviour that messages sent at once - this is message batching working. I think there is some other problem - could you look at Centrifugo server logs, there could be a reason of `invalid message` response.

**Comment by FZambia** [comment]
Closing for now - please, reopen if this is still actual!
