### ISSUE TITLE
Wrong typing of subscription error context

### ISSUE THREAD

**Issue by cailloumajor** [centrifugal/centrifuge-js#185]
First of all, hello and thank you for Centrifugo and its ecosystem.

The current type definition for subscription error context (see below) is not correct.
https://github.com/centrifugal/centrifuge-js/blob/2c7858166cd6f8917dcd3f71e2c8067394794261/dist/centrifuge.d.ts#L141-L145

Given how this context is built:
https://github.com/centrifugal/centrifuge-js/blob/2c7858166cd6f8917dcd3f71e2c8067394794261/src/subscription.js#L195-L200

it does not include an `error` string property, it is built from the error received from Centrifugo server, which is a client protocol error object, shaped as below (https://github.com/centrifugal/protocol/blob/3a5482c312c2131335ebdc755c167e59902a9506/definitions/client.proto#L7-L11)
```Protobuf
message Error {
  uint32 code = 1;
  string message = 2;
  bool temporary = 3;
}
```

If you agree, I would be happy to submit a PR.

**Comment by FZambia** [comment]
Hello @cailloumajor 

Thanks, you are right - it's incorrect.

The only thing is that `bool temporary = 3;` is only used in [client protocol v2](https://github.com/centrifugal/centrifuge-js/pull/186) I am actively working on during last several month. So only `code` and `message` should be available for current protocol/API version.
