### ISSUE TITLE
how to subscribe-since-known-position?

### ISSUE THREAD

**Issue by wideweide** [centrifugal/centrifuge-js#188]
I write some code just follow: https://github.com/centrifugal/centrifuge-js#subscribe-since-known-position
I used 2.8.5:  https://cdn.jsdelivr.net/gh/centrifugal/centrifuge-js@2.8.5/dist/centrifuge.min.js

```
    const subscription = centrifuge.subscribe(
        channel,
        function (message) {
            console.log(message);
            document.getElementById('info').innerHTML += '<br/>' + message.offset + ' : ' + message.data
        },
        { 'since': { 'offset': 0, 'epoch': '<EPOCH>' } } 
    );
```

The first question is : `<EPOCH>`  can be null? or just use the string` <EPOCH>`?  In first time to subscribe, I have no epoch..,or since can only be used when reconnect ?

I tryed since offset=0 or recently offset (subscription.history - 5), expected to receive history message,but noting..

Where am I doing wrong?

**Comment by FZambia** [comment]
Closing since no response from OP
