### ISSUE TITLE
updating event callbacks for a subscription

### ISSUE THREAD

**Issue by lmj0011** [centrifugal/centrifuge-js#19]
I have several subscriptions stored in a Map structure.
They are created like this:

```js
//create subscriptions to all registered users, then add to Map
      centrifuge.startAuthBatching();

//this.userCallbacks  is an object containing the event functions
      this.app.users.forEach(user=> {
        let usrSub = centrifuge.subscribe(`$${user.id}`, this.userCallbacks);
        this.subscriptionMap.set(user.id, usrSub);

      });

      centrifuge.stopAuthBatching();
```

What I want to do is update one of the callbacks for all user subscriptions later on.
This is how I attempt to do this:

Note: This happens on a `click` event.
```js
this.subscriptionMap.forEach(sub=> {
      sub.on('message', _=> {
        console.log({newMessage: _});
      });
    });
```

However, this method seems to compound the `message` callback which causes the function to be called multiple times. I'm expecting it to overwrite the previous `message` callback

**Comment by FZambia** [comment]
Hi, I think you can just check your own variable in message callback and make it behave like you want:
```javascript
      function userCallbacks() {
         if SOME_VARIABLE {

        } else {

        }
     }

      this.app.users.forEach(user=> {
        let usrSub = centrifuge.subscribe(`$${user.id}`, this.userCallbacks);
        this.subscriptionMap.set(user.id, usrSub);

      });
```

Then on click change that `SOME_VARIABLE`. Does it make sense?

Also I have not tried it by myself before - but maybe calling `off` method on `sub` can help? Internally subscription is an [EventEmitter](https://github.com/Olical/EventEmitter).

**Comment by lmj0011** [comment]
I will try both of your suggestions.

`this.userCallbacks` // is an object containing the event functions

**Comment by FZambia** [comment]
Ah, I see, anyway trick with variable should help (if write it in `message` function of that object).

**Comment by lmj0011** [comment]
This works in achieving what I want. (updating the callback of a subscription)

```js
this.subscriptionMap.forEach(sub=> {
      sub.removeEvent('message')
      .on('message', _=> {
        console.log({newMessage: _});
      });
    });
```
you might want to include a reference to the EventEmitter API somewhere in Centrifugo docs, if it's not there already.
https://github.com/Olical/EventEmitter/blob/master/docs/api.md

**Comment by FZambia** [comment]
Cool! Yes, I will update docs

**Comment by FZambia** [comment]
Fixed in https://github.com/centrifugal/documentation/commit/084050eb3461120062733e1d4b5f8cbbf6b4296b
