### ISSUE TITLE
Is it possible to get rooms available for a certain date (date period)?

### ISSUE THREAD

**Issue by mr-mister-bit** [centrifugal/centrifuge-js#191]
ex. rooms->getFreeByDate("2017-06-21 15:00:00", "2017-06-21 19:30:00") ?

**Comment by FZambia** [comment]
Hello! The question seems absolutely irrelevant to this repo. Maybe you have posted the question to the wrong place? This is not supported, and I do not understand how this is related to `centrifuge-js` (so won't be supported in the future too).
