### ISSUE TITLE
Disconnected with error 3501

### ISSUE THREAD

**Issue by AlloYEx** [centrifugal/centrifuge-js#196]
centrifuge.on('connecting', function (ctx) {
      console.log(`connecting: ${ctx.code}, ${ctx.reason}`);
    }).on('connected', function (ctx) {
      console.log(`connected over ${ctx.transport}`);
    }).on('disconnected', function (ctx) {
      console.log(`disconnected: ${ctx.code}, ${ctx.reason}`);
    }).connect();

in console: 
client credentials not found client=cdac32e4-b8e8-4cda-965c-62911fc34ddb user=
disconnect after handling command client=cdac32e4-b8e8-4cda-965c-62911fc34ddb command="id:1  connect:{name:\"js\"}" reason="bad request" user=
getting this error from console: disconnected: 3501, bad request. What i need to do?

**Comment by FZambia** [comment]
Hello!

```
client credentials not found
```

This means you have not provided JWT - https://centrifugal.dev/docs/server/authentication or not using https://centrifugal.dev/docs/server/proxy#connect-proxy. These are two ways to authenticate connection in Centrifugo.

Without authentication Centrifugo does not accept connection. Check out https://centrifugal.dev/docs/getting-started/quickstart

You can also set `"client_insecure": true` [option](https://centrifugal.dev/docs/3/server/configuration#insecure-client-connection) in Centrifugo configuration – to disable most authentication checks, but it must not be used in production.

Please ask questions [in community rooms](https://centrifugal.dev/docs/3/getting-started/introduction#join-community)
