### ISSUE TITLE
How can I hide the secret key in javascript?

### ISSUE THREAD

**Issue by Khailz** [centrifugal/centrifuge-js#2]
I am using Django and am rendering all of my centrifuge javascript in html. I don't want my secret key to be shown in view source but you need it there to generate client tokens. What can I do?

**Comment by FZambia** [comment]
Hello, tokens must never be generated on client side as only application backend and Centrifugo itself must know secret key. I generated token in some client-side example using secret key only for demo purposes. 

2 ways here: run Centrifugo in `insecure` mode as it won't check any tokens or if you don't have backend and users you can pre-generate token for anonymous user and put it in Javascript.

The main question - does your application has any backend?

**Comment by FZambia** [comment]
Ah, sorry have not noticed that you wrote about Django - you just generate token in a view or context processor for current user and put it into template

**Comment by Khailz** [comment]
I see thank you very much, I just recently learned how to render context into templates.
