### ISSUE TITLE
does this library support 2.8.7 ?

### ISSUE THREAD

**Issue by garyng2000** [centrifugal/centrifuge-js#200]
it fails on connect at centrifuge.ts like 1297.

By examine the return, it seems that the return is there but that line failed with access client of undefined.

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'client')
    at Centrifuge._connectResponse (centrifuge.ts:1297:1)
    at centrifuge.ts:832:1

 below are result capture by chrome's dev console

{id: 1, result: {client: "97d432f1-5177-4cd9-b5fb-dc8cef861206", version: "2.8.7"}

**Comment by FZambia** [comment]
Hello!

centrifuge-js v3 works only with Centrifugo v4, for Centrifugo v2 and Centrifugo v3 you should use centrifuge-js v2.x.
