### ISSUE TITLE
on internet reconnect, centriguge-js take approx 1 min for reconnection to centrifuge server

### ISSUE THREAD

**Issue by paliwalsam** [centrifugal/centrifuge-js#203]
Hii,

when client internet connection change, centriguge-js take approx 1 min for reconnection to centrifuge server,

i am using websocket transport system,following configuration does not provide any help
        minReconnectDelay:50,
	maxReconnectDelay:100,
	maxServerPingDelay:100,

**Comment by FZambia** [comment]
Hello, It can take up to 35 secs in default configuration (25 secs for ping wait, additional 10 secs coming from default maxPingDelay), can you provide steps to reproduce 1 min?

Also, please describe which environment and client/server versions you are using? As I am talking about latest versions while you could use old version of centrifuge-js.

As a workaround for a long time to reconnect it's possible to use online/offline events https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine - and disconnect/connect upon receiving them.

Seems we should rely on those events in `centrifuge-js` too to force faster reconnect on going `online`.

**Comment by paliwalsam** [comment]
server : ubuntu 20.04
centrifuge server: 4.0.1
centrifuge JS client: 3.0.1
chrome Version 105.0.5195.125 (Official Build) (arm64)
 after implementation following:
  
function  reconnect()
{
	centrifuge.disconnect();
	centrifuge.connect();
}
 
window.addEventListener('offline', (e) => { console.log('offline'); });
window.addEventListener('online',  (e) => { console.log('online');reconnect();   });

 
after above implementation, no luck

**Comment by FZambia** [comment]
> can you provide steps to reproduce 1 min?

Still actual

**Comment by FZambia** [comment]
> window.addEventListener('offline', (e) => { console.log('offline'); });
> window.addEventListener('online', (e) => { console.log('online');reconnect(); });

> after above implementation, no luck

Tried this locally – this causes reconnect for me upon getting `online` event, what's exactly going on in your case? Why `no luck`? Please try providing as much of the context as you can - `no luck` does not describe anything.

**Comment by FZambia** [comment]
@paliwalsam hello, I believe that #204 should make things much better, but I still confused why it did not help in your case.
