### ISSUE TITLE
sub.send message doesn't pass "Sender Information"

### ISSUE THREAD

**Issue by StarMonk** [centrifugal/centrifuge-js#209]
**Describe the bug**
When a user is subscribed to a channel with a JWT token and then a message is sent to the channel using `sub.send`, there is no way currently to know, who sent that messages on the other end of the channels

**To Reproduce**
1. Subscribe to Channel
2. Send a message "sub.send"
3. Receive a message on other ends
4. Who sent that message, no information is available only payload is available

**Expected behavior**
I was expecting the "userId" that is passed on the token (sub) will be visible or available on the other end to identify the message's author.

**Versions**
 - OS: [e.g. MacOS] - Linux Ubuntu
 - Browser or environment with version [e.g. chrome 97.4, NodeJS 18.0.2, React-Native 0.10.0] - Chrome Latest
 - Centrifuge client version [e.g. 3.1.0
 - Server version e.g. 4.0.1

**Additional context**
Is there any way, Centrifuge can also send a Timestamp on Each message?

**Comment by FZambia** [comment]
Hello, @StarMonk 

Subscription does not have `send` method. Do you mean `publish`? I suppose yes.

Please read the section about [idiomatic Centrifugo usage](https://centrifugal.dev/docs/getting-started/design#idiomatic-usage). Centrifugo's main paradigm is that final message payload is generated by the backend. So you can add timestamp and user id yourself after validating request from the client and constructing real-time message.

But anyway, if the messages published from the client side without backend involved into the process (is it the case you have? publishing messages without backend involved right?), it should contain `user id` inside `info` field of Publication - https://github.com/centrifugal/centrifuge-js/blob/e878efb866bed415215f72aa8f0d4013778aa4bf/src/types.ts#L172. Do you have it or it's missing?

**Comment by StarMonk** [comment]
I never thought about this - This is not a 1 million WebSocket scalable situation. We are dropping the centrifuge for now and moving to uWebsocket.

Thanks

![image](https://user-images.githubusercontent.com/49620018/208522814-cf6a3fd0-7433-443a-8362-347db592bafb.png)

**Comment by FZambia** [comment]
As a side note, we used this approach to build a chat system with 1 million concurrent users. Good luck with uWebsocket - it's an awesome low-level library and you can build everything on top of it.
