### ISSUE TITLE
How to unset token if have getToken method ?

### ISSUE THREAD

**Issue by evdevru** [centrifugal/centrifuge-js#219]
I want to unset token to use as anonym. But function getToken() dont allow to return null. How i can unset token ?

Use case: logout system

Yes, i can create new instance. But in that case i loose all active public subscriptions.

version: 3.1.0

**Comment by FZambia** [comment]
Hello, could you describe in more detail what you are doing on logout?

It's not possible to change user on the fly in Centrifugo without reconnect, so you need to disconnect anyway. Do I understand right that what you want to achieve is:

* Disconnect on logout
* Unsubscribe from non-public channels
* Somehow unset token
* Connect again with empty (?) token

So I want to understand the exact flow you expect to work.

Since there are many options on the server side related to auth I need to understand your server configuration also.

**Comment by evdevru** [comment]
> Hello, could you describe in more detail what you are doing on logout?
> 
> It's not possible to change user on the fly in Centrifugo without reconnect, so you need to disconnect anyway. Do I understand right that what you want to achieve is:
> 
> * Disconnect on logout
> * Unsubscribe from non-public channels
> * Somehow unset token
> * Connect again with empty (?) token
> 
> So I want to understand the exact flow you expect to work.
> 
> Since there are many options on the server side related to auth I need to understand your server configuration also.

Yes, you are understood correctly. But in cetnrifugo v3 dont have methods to change token. If you are disconnect and reconnect again method getToken() dont calls more. For solve that i call method _refresh() and after that connect again.
Its working if you have guest token (like user with ID=0). But i want to disconnect from socket with token and connect to socket WITHOUT token.

**Comment by FZambia** [comment]
Let me think a bit here, definitely want to fix this case - trying to find a solution, most probably need to re-imagine SDK behaviour regarding empty tokens from getToken.

**Comment by FZambia** [comment]
@evdevru hello, could you take a look at #223 ? I am trying to find out API which may solve this case - would be great to evaluate the approach over real scenario.

**Comment by evdevru** [comment]
> @evdevru hello, could you take a look at #223 ? I am trying to find out API which may solve this case - would be great to evaluate the approach over real scenario.

Hi! Yes, its right if public subscriptions is alive after reconnect

**Comment by FZambia** [comment]
> Hi! Yes, its right if public subscriptions is alive after reconnect or can restore them

Hello @evdevru . I don't know the exact logic you have, so better if you extrapolate your real use case to the proposed API changes. It will be much harder to change after merging. In general subscription state is kept inside client after resetting a token. It's possible to unsubscribe from some subscriptions (which are not public) while disconnected. Then after disconnecting with token reset and calling connect - all subscriptions left will be re-established automatically.

**Comment by evdevru** [comment]
> > Hi! Yes, its right if public subscriptions is alive after reconnect or can restore them
> 
> Hello @evdevru . I don't know the exact logic you have, so better if you extrapolate your real use case to the proposed API changes. It will be much harder to change after merging. In general subscription state is kept inside client after resetting a token. It's possible to unsubscribe from some subscriptions (which are not public) while disconnected. Then after disconnecting with token reset and calling connect - all subscriptions left in the client's registry will be re-established automatically.

Yes, its right logic
