### ISSUE TITLE
unsubscribe event triggered when attempting to subscribed to 100+ channels

### ISSUE THREAD

**Issue by lmj0011** [centrifugal/centrifuge-js#23]
**centrifuge@1.3.8**

I have around 350 channels I attempt to subscribe to, on initialization of my app.

I make the request for these subscriptions in between
the `startAuthBatch()` and  `stopAuthBatch()` functions. (channels are private)

```js
this.centrifuge.startAuthBatching();

        this.authChannels.forEach(channel => {
          let userSub = this.centrifuge.subscribe(channel.name, SubCallbacks);
          this.userMap.set(channel.name, userSub);
        });

  this.centrifuge.stopAuthBatching();
```

When I check out the console I get this.

![err1](https://cloud.githubusercontent.com/assets/9396189/20909110/393b9466-bb1f-11e6-8965-b9b12ed0cbe6.png)

![err2](https://cloud.githubusercontent.com/assets/9396189/20909113/3c94d8f2-bb1f-11e6-9ff6-518b4a664b22.png)

This wasn't a problem until recently so I don't believe the amount of subscriptions has anything to do with it.

**Comment by FZambia** [comment]
Hello

Looks like you publish into channel before Centrifugo returned subscription success ack - see https://github.com/centrifugal/centrifuge-js/blob/1.3.8/src/centrifuge.js#L1491. If so - wait for  subscription `subscribe` event before publishing. 

Btw - there is a limit in Centrifugo - 100 channels max per client, have you tuned it to achieve 350 channels per one client?

**Comment by lmj0011** [comment]
>Btw - there is a limit in Centrifugo - 100 channels max per client

is this somewhere in the docs?

>have you tuned it to achieve 350 channels per one client?

I haven't, due to a recent change on my part, I'm trying to subscribe to an unknown amount of channels.

**Comment by FZambia** [comment]
No, I added this limit to prevent spaming Centrifugo with subscriptions coming from one client - have not thought someone will use more than 20-30 channels in application. This is a `client_channel_limit` configuration file option.

Looks like it's time to document all available options.

**Comment by lmj0011** [comment]
I updated my config file to the following:

```json
{
   "secret": "377b1e36-xxxx-xxxx-xxxx-1e3effeaf29d",
   "connection_lifetime": 7200,
    "publish": true,
    "watch": true,
    "presence": true,
    "join_leave": true,
    "history_size": 500,
    "history_lifetime": 7889232,
    "client_channel_limit": 1000
}
```

The same errors occur.
Is centrifugo coded to read the `client_channel_limit` property from the config file?

>Looks like you publish into channel before Centrifugo returned subscription success ack

I'm only making the subscription and storing it inside a Map structure.
No publishing took place in that snippet.

**Comment by FZambia** [comment]
> No publishing takes place before the errors occur

Yes, I mean that this error most probably happens when you try to publish to subscription that is not acknowledged by Centrifugo yet. You can start publishing only after `subscribe` event triggered.

**Comment by lmj0011** [comment]
>No publishing takes place before the errors occur

When you say "publish" are you referring to sending a message or attempting to subscribe to another channel?

Because I have not published any message to the channel when that error occurs.

**Comment by lmj0011** [comment]
If there's nothing to be done for this issue, it can be closed.

After finding out about the `client_channel_limit` and what the default is, I'm looking to redesign my app to avoid this situation.

**Comment by FZambia** [comment]
This error can also happen if you call presence (https://github.com/centrifugal/centrifuge-js/blob/1.3.8/src/centrifuge.js#L1518) or history (https://github.com/centrifugal/centrifuge-js/blob/1.3.8/src/centrifuge.js#L1544) before subscription ready.

**Comment by lmj0011** [comment]
ok, I see now. It got hung up on one of calls to presence()

**Comment by FZambia** [comment]
I tried to reproduce this - presence, publish and history work nice in my case even without waiting `subscribe` event.

Maybe those errors happened because your app could not subscribe on many subscriptions because of limit?

**Comment by lmj0011** [comment]
yea, I think it's the limit because it seemed to only error after a certain amount

**Comment by lmj0011** [comment]
but looking at the screenshot, none all of those subscriptions were getting subscribed

**Comment by lmj0011** [comment]
is it ok to call a method like presence() or history() inside of join/leave event for one subscription?

**Comment by FZambia** [comment]
I don't see any reasons against. Let's wait if this error will reproduce with changed channel limit then?

**Comment by lmj0011** [comment]
>I don't see any reasons against. Let's wait if this error will reproduce with changed channel limit then?

I up'd it earlier to `1000`, and still got the same errors

**Comment by FZambia** [comment]
I think I need to look at your code then - I can not reproduce it

**Comment by lmj0011** [comment]
It will take me more time than I would like to spend, to recreate this issue in a way that does reveal my company's code. We can count it as bad design and close the issue. If something similiar happens again, I will recreate it.

**Comment by FZambia** [comment]
ok, in short this can happen if subscription is in UNSUBSCRIBED state - when we call `subscribe` subscription goes to SUBSCRIBING state - so this error can occur if presence called for subscription that was already unsubscribed - looking at source code of js client this can happen when `unsubscribe` method called or after disconnect

**Comment by FZambia** [comment]
Channel limit will be documented soon: https://github.com/centrifugal/documentation/pull/11/commits/4ec354589b4b08d1db808dcd2ce175c9b7ddf3ba
