### ISSUE TITLE
不支持微信小程序

### ISSUE THREAD

**Issue by leblog** [centrifugal/centrifuge-js#231]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions**
 - OS: [e.g. MacOS]
 - Browser or environment with version [e.g. chrome 97.4, NodeJS 18.0.2, React-Native 0.10.0]
 - Centrifuge client version [e.g. 3.0.1]
 - Server version [e.g. 4.0.1]

**Additional context**

**Comment by FZambia** [comment]
Closing - no response from op for a long time.
