### ISSUE TITLE
CommonJS Alternative

### ISSUE THREAD

**Issue by aaronflorey** [centrifugal/centrifuge-js#232]
**Is your feature request related to a problem? Please describe.**
We are using Vite for our project which doesn't support CommonJS modules, so i'm unable to use this package in my project. 

I've tried enabling optimizations and commonjs plugins in Vite, but they don't work for some reason.

I was able to get it working by downloading the repo, changing tsconfig.json "module" to esnext allowed me to use the package.

**Describe the solution you'd like**
Another build of the project suited to ESM

**Comment by FZambia** [comment]
Hello @aaronflorey 

Please provide steps to reproduce - i.e show commands how to start the project where importing Centrifuge is not possible.

**Comment by FZambia** [comment]
BTW, we have example which is built with Vite: https://github.com/centrifugal/examples/tree/master/v4/keycloak_sso_auth - probably you have different configuration/version or sth. So steps to reproduce with specific version would really help here.

**Comment by FZambia** [comment]
This should be solved with centrifuge-js v5: https://github.com/centrifugal/centrifuge-js/releases/tag/5.0.0
