### ISSUE TITLE
Centrifuge connection

### ISSUE THREAD

**Issue by Howlnvisible** [centrifugal/centrifuge-js#236]
**Describe the bug**
I'm trying to connect to centrifuge in my React Native app, but when I'm logging to the console my centrifuge it is saying: 'state: connecting'. I've been trying to implement the connection for chats as well as for notifications, both doesn't work. I'm doing the same implementation for the web on React and it does work perfectly. 

**Versions**
-  "react": "18.2.0"
- "react-native": "0.71.8"
-  "centrifuge": "^4.0.0"

**code snippet**

const Notifications = () => {
  const dispatch = useDispatch();
  const centrifuge = useRef(null);
  const channelRef = useRef(null);
  const toast = useToast();
  const { notifications } = useSelector((state) => state.notifications_tokens);
  console.log(`notifications`, notifications);
  
  useEffect(() => {
    dispatch(fetchGenerateSystemToken());
  }, []);

  useEffect(() => {
    centrifuge.current = new Centrifuge(
      "wss://prod.mazzon.ru/centrifugo/connection/websocket",
      {
        token: notifications.token,
      }
    );
    const newCentrifuge = centrifuge.current;
    newCentrifuge.connect();
    console.log(`centrifuge.current`, centrifuge.current);
  }, [notifications.token]);

    useEffect(() => {
      if (centrifuge.current) {
        if (channelRef.current) {
          channelRef.current.unsubscribe();
          centrifuge.current.removeSubscription(channelRef.current);
        }

        channelRef.current = centrifuge.current.newSubscription(notifications.channel, {
          token: notifications.channel_token
        });
        console.log(`channelRef.current`, channelRef.current);

        channelRef.current.on('publication', (ctx) => {
          const notifications = ctx.data;
          console.log('notifications', notifications);
          toast.show({
              description: notifications.body,
              placement: 'bottom',
              duration: 2000
          })
        }).subscribe();

        return () => {
          channelRef.current.unsubscribe();
        };
      }
    }, [centrifuge.current])
  return <></>;
};

**Comment by vuphamdirox** [comment]
I have the same issue with stuck at "connecting". @Howlnvisible have you resolved it? 
Could you sharing some tips for me?

Best regards,
Vu

**Comment by Howlnvisible** [comment]
> I have the same issue with stuck at "connecting". @Howlnvisible have you resolved it? Could you sharing some tips for me?
> 
> Best regards, Vu

Hello. This is still an issue for me

**Comment by FZambia** [comment]
Hey guys, not enough info to help.

About React Native - I tried to run the client using `expo` in web environment as described in https://github.com/centrifugal/centrifuge-js/issues/224#issuecomment-1538820023 - and it works (no need to use custom WebSocket constructor if you don't need custom header).

Try to subscribe on 'error' event - probably it will show sth useful. Also look at server logs (enable debug level).

I can not provide more exact advice since there could be many potential issues actually and without simple reproducer I can only guess what strikes in your particular cases.

**Comment by vuphamdirox** [comment]
Hi @FZambia 
I would like to share some configuration on server and client in below:

- on server. I tried to change this setting 
`client_insecure: true`
  `use_client_protocol_v1_by_default: true`
`allow_anonymous_connect_without_token: true`
- on client(reactjs): 
`  const client = new Centrifuge(url ,{ debug: true , version: '4.0.0' });

        client.on('connecting', function(ctx) {
            console.log('connecting', ctx);
        });

        client.on('connected', function(ctx) {
            console.log('connected', ctx);
        });
        client.on('error', function(ctx) {
            console.log('error', ctx);
        });

        client.on('disconnected', function(ctx) {
            console.log('disconnected', ctx);
        });
       
        client.connect();`

It shows me the error message:
`code: 1 message: "timeout"`

What's missing on configuration on server or steps?
Best regards,
Vu

**Comment by Howlnvisible** [comment]
> Hey guys, not enough info to help.
> 
> About React Native - I tried to run the client using `expo` in web environment as described in [#224 (comment)](https://github.com/centrifugal/centrifuge-js/issues/224#issuecomment-1538820023) - and it works (you need to provide proper token, no need to use custom WebSocket constructor if you don't need custom header).
> 
> Try to add on 'error' event handler - probably it will show sth useful. Also look at server logs (enable debug level).
> 
> I can not provide more exact advice since there could be many potential issues actually and without simple reproducer I can only guess what strikes in your particular cases.

Im doing it on mobile, not web. I tried to do logs above and this is the logs im getting. 

notifications 
config Object {
  "data": null,
  "debug": true,
  "emulationEndpoint": "/emulation",
  "eventsource": null,
  "fetch": null,
  "getData": null,
  "getToken": null,
  "maxReconnectDelay": 20000,
  "maxServerPingDelay": 10000,
  "minReconnectDelay": 500,
  "name": "js",
  "networkEventTarget": null,
  "protocol": "json",
  "readableStream": null,
  "sockjs": null,
  "sockjsOptions": Object {},
  "timeout": 5000,
  "token": undefined,
  "version": "4.0.0",
  "websocket": null,
}
connect called
start connecting
client state disconnected -> connecting
connecting Object {
  "code": 0,
  "reason": "connect called",
}
start reconnecting
client will use websocket
id of transport 1
centrifuge.current Centrifuge {
  "_batching": false,
  "_callbacks": Object {},
  "_client": null,
  "_commandId": 0,
  "_commands": Array [],
  "_config": Object {
    "data": null,
    "debug": true,
    "emulationEndpoint": "/emulation",
    "eventsource": null,
    "fetch": null,
    "getData": null,
    "getToken": null,
    "maxReconnectDelay": 20000,
    "maxServerPingDelay": 10000,
    "minReconnectDelay": 500,
    "name": "js",
    "networkEventTarget": null,
    "protocol": "json",
    "readableStream": null,
    "sockjs": null,
    "sockjsOptions": Object {},
    "timeout": 5000,
    "token": undefined,
    "version": "4.0.0",
    "websocket": null,
  },
  "_currentTransportIndex": 0,
  "_data": null,
  "_debugEnabled": true,
  "_decoder": JsonDecoder {},
  "_deviceWentOffline": false,
  "_dispatchPromise": Promise {
    "_h": 0,
    "_i": 1,
    "_j": undefined,
    "_k": null,
  },
  "_emulation": false,
  "_encoder": JsonEncoder {},
  "_endpoint": "my websocket url here",
  "_events": Object {
    "connected": [Function anonymous],
    "connecting": [Function anonymous],
    "disconnected": [Function anonymous],
    "error": Array [
      [Function anonymous],
      [Function anonymous],
    ],
    "state": [Function anonymous],
  },
  "_eventsCount": 5,
  "_maxListeners": undefined,
  "_networkEventsSet": false,
  "_node": "",
  "_promiseId": 0,
  "_promises": Object {},
  "_reconnectAttempts": 0,
  "_reconnectTimeout": null,
  "_reconnecting": true,
  "_refreshRequired": false,
  "_refreshTimeout": null,
  "_sendPong": false,
  "_serverPing": 0,
  "_serverPingTimeout": null,
  "_serverSubs": Object {},
  "_session": "",
  "_subs": Object {},
  "_token": undefined,
  "_transport": WebsocketTransport {
    "_transport": WebSocket {
      "CLOSED": 3,
      "CLOSING": 2,
      "CONNECTING": 0,
      "OPEN": 1,
      "_eventEmitter": NativeEventEmitter {
        "_nativeModule": Object {
          "addListener": [Function nonPromiseMethodWrapper],
          "close": [Function nonPromiseMethodWrapper],
          "connect": [Function nonPromiseMethodWrapper],
          "getConstants": [Function anonymous],
          "ping": [Function nonPromiseMethodWrapper],
          "removeListeners": [Function nonPromiseMethodWrapper],
          "send": [Function nonPromiseMethodWrapper],
          "sendBinary": [Function nonPromiseMethodWrapper],
        },
      },
      "_socketId": 2,
      "_subscriptions": Array [
        Object {
          "remove": [Function remove],
        },
        Object {
          "remove": [Function remove],
        },
        Object {
          "remove": [Function remove],
        },
        Object {
          "remove": [Function remove],
        },
      ],
      "readyState": 0,
      "url": "my websocket url here",
    },
    "endpoint": "my websocket url here",
    "options": Object {
      "websocket": [Function WebSocket],
    },
  },
  "_transportClosed": false,
  "_transportId": 1,
  "_transportWasOpen": false,
  "_transports": Array [],
  "_triedAllTransports": false,
  "state": "connecting",
}
channelRef.current Subscription {
  "_centrifuge": Centrifuge {
    "_batching": false,
    "_callbacks": Object {},
    "_client": null,
    "_commandId": 0,
    "_commands": Array [],
    "_config": Object {
      "data": null,
      "debug": true,
      "emulationEndpoint": "/emulation",
      "eventsource": null,
      "fetch": null,
      "getData": null,
      "getToken": null,
      "maxReconnectDelay": 20000,
      "maxServerPingDelay": 10000,
      "minReconnectDelay": 500,
      "name": "js",
      "networkEventTarget": null,
      "protocol": "json",
      "readableStream": null,
      "sockjs": null,
      "sockjsOptions": Object {},
      "timeout": 5000,
      "token": undefined,
      "version": "4.0.0",
      "websocket": null,
    },
    "_currentTransportIndex": 0,
    "_data": null,
    "_debugEnabled": true,
    "_decoder": JsonDecoder {},
    "_deviceWentOffline": false,
    "_dispatchPromise": Promise {
      "_h": 0,
      "_i": 1,
      "_j": undefined,
      "_k": null,
    },
    "_emulation": false,
    "_encoder": JsonEncoder {},
    "_endpoint": "my websocket url here",
    "_events": Object {
      "connected": [Function anonymous],
      "connecting": [Function anonymous],
      "disconnected": [Function anonymous],
      "error": Array [
        [Function anonymous],
        [Function anonymous],
      ],
      "state": [Function anonymous],
    },
    "_eventsCount": 5,
    "_maxListeners": undefined,
    "_networkEventsSet": false,
    "_node": "",
    "_promiseId": 0,
    "_promises": Object {},
    "_reconnectAttempts": 0,
    "_reconnectTimeout": null,
    "_reconnecting": true,
    "_refreshRequired": false,
    "_refreshTimeout": null,
    "_sendPong": false,
    "_serverPing": 0,
    "_serverPingTimeout": null,
    "_serverSubs": Object {},
    "_session": "",
    "_subs": Object {
      "undefined": [Circular],
    },
    "_token": undefined,
    "_transport": WebsocketTransport {
      "_transport": WebSocket {
        "CLOSED": 3,
        "CLOSING": 2,
        "CONNECTING": 0,
        "OPEN": 1,
        "_eventEmitter": NativeEventEmitter {
          "_nativeModule": Object {
            "addListener": [Function nonPromiseMethodWrapper],
            "close": [Function nonPromiseMethodWrapper],
            "connect": [Function nonPromiseMethodWrapper],
            "getConstants": [Function anonymous],
            "ping": [Function nonPromiseMethodWrapper],
            "removeListeners": [Function nonPromiseMethodWrapper],
            "send": [Function nonPromiseMethodWrapper],
            "sendBinary": [Function nonPromiseMethodWrapper],
          },
        },
        "_socketId": 2,
        "_subscriptions": Array [
          Object {
            "remove": [Function remove],
          },
          Object {
            "remove": [Function remove],
          },
          Object {
            "remove": [Function remove],
          },
          Object {
            "remove": [Function remove],
          },
        ],
        "readyState": 0,
        "url": "my websocket url here",
      },
      "endpoint": "my endpoint here",
      "options": Object {
        "websocket": [Function WebSocket],
      },
    },
    "_transportClosed": false,
    "_transportId": 1,
    "_transportWasOpen": false,
    "_transports": Array [],
    "_triedAllTransports": false,
    "state": "connecting",
  },
  "_data": null,
  "_epoch": null,
  "_events": Object {
    "error": [Function anonymous],
    "state": [Function anonymous],
  },
  "_eventsCount": 2,
  "_getData": null,
  "_getToken": null,
  "_inflight": false,
  "_joinLeave": false,
  "_maxListeners": undefined,
  "_maxResubscribeDelay": 20000,
  "_minResubscribeDelay": 500,
  "_offset": null,
  "_positioned": false,
  "_promiseId": 0,
  "_promises": Object {},
  "_recover": false,
  "_recoverable": false,
  "_refreshTimeout": null,
  "_resubscribeAttempts": 0,
  "_resubscribeTimeout": null,
  "_token": "",
  "channel": undefined,
  "state": "unsubscribed",
}
subscription state undefined unsubscribed -> subscribing
subscribing on undefined
delay subscribe on undefined till connected
websocket transport open
subscribing on undefined
websocket transport closed
client state connecting -> disconnected
disconnected Object {
  "code": 3501,
  "reason": "bad request",
}
closing existing transport
subscribing on undefined
delay subscribe on undefined till connected

**Comment by FZambia** [comment]
Look at server logs on debug level - it may give you tips what's going on. I see disconnect code 3501 in logs, this means server received your connection attempt.

**Comment by FZambia** [comment]
Closing, no response from OP for a long time and no steps to reproduce. Bad request in from server means that sth wrong with configuration.
