### ISSUE TITLE
Call disconnect then refresh reconnects

### ISSUE THREAD

**Issue by JeanCarriere** [centrifugal/centrifuge-js#24]
Even if the disconnect function is explicitly called, the refresh mechanism automatically reconnects.
It shouldn't in this case.

**Comment by FZambia** [comment]
Hello, thanks for bug report!

I made a fix in 1.3.9 tag branch - could you check it out? If it works - I'll publish it to npm.

**Comment by JeanCarriere** [comment]
It works 👍

**Comment by FZambia** [comment]
Great! Published and merged into master.
