### ISSUE TITLE
Wrong type of ServerPublicationContext.tags

### ISSUE THREAD

**Issue by frolovsky** [centrifugal/centrifuge-js#243]
**Describe the bug**
On publication event you got context with type `ServerPublicationContext`. This type got property tags?: `Map<string, string>;`. But as I see the type does not correspond to reality. Most likely it should be `Record<string, string>` or `Record<string, any>`.

**To Reproduce**
1. Get publication with filled tags
2. Try to get property of tags as Map (`ctx.tags?.get("some_key")`;
3. See error

**Expected behavior**
Type of `tags` must be `Record`

**Screenshots**

**Versions**
 - Centrifuge client version [3.1.0]
 - Server version [4.0.1]

**Comment by FZambia** [comment]
@frolovsky hello, thanks for pointing!

I made a change in #244, do you need the same fix for centrifuge-js v3.x?

**Comment by frolovsky** [comment]
Thank you! we will update to 4 version soon, so 3 version don't need.
