### ISSUE TITLE
ES modules import fails

### ISSUE THREAD

**Issue by HJK181** [centrifugal/centrifuge-js#245]
**Describe the bug**
Can't import Centrifuge as ES module:
```
SyntaxError: The requested module '../node_modules/centrifuge/build/index.js' does not provide an export named 'Centrifuge'
```

**To Reproduce**
Just add an import as described in the docs: `import { Centrifuge } from 'centrifuge';`

**Expected behavior**
ES modules import works.

**Versions**
 - Browser or environment with version [e.g. Chrome Version 116.0.5845.110 (Offizieller Build) (64-Bit)]
 - Centrifuge client version [^4.1.0]

**Comment by FZambia** [comment]
Hello @HJK181 

Please provide steps to reproduce, minimal project initialization steps to reproduce the issue will works

**Comment by HJK181** [comment]
Hi @FZambia 

we are on a pretty old Polymer stack and I'm not very familiar with their handling of imports. All I know is that they are using their own development server https://github.com/Polymer/tools/tree/master/packages/polyserve

I've created a simple example application https://github.com/HJK181/centrifuge-js-245/tree/master
Just start the application by running `npm start` and navigate to http://localhost:8081/view1 to see the error. The import can be found in `src/my-view1.js`.

**Comment by FZambia** [comment]
Addressing this in #247 . I believe I already made it work with ESM and CommonJS. The provided demo repo works fine with a new build.

The hard part though is that we also provide Protobuf format support with `centrifuge-js` and we need to make sure that users that use Centrifuge with JSON format do not have ProtobufJS in the final build. Making ProtobufJS work with different environments was rather challenging and most probably we will have new major version bump - which will require some import string changes for users of Protobuf format.

**Comment by FZambia** [comment]
@HJK181 just released v5 beta version: https://www.npmjs.com/package/centrifuge/v/5.0.0-beta.0

Now need some time to check some scenarios, prepare proper release and then we are good to go.

**Comment by HJK181** [comment]
Suceffully tested the beta release. No hurries with the release I also need more time to polish the integration, setup a cluster in Kubernetes, etc.

**Comment by FZambia** [comment]
@HJK181 v5 is released: https://github.com/centrifugal/centrifuge-js/releases/tag/5.0.0

Please let me know if sth won't properly work with the release.
