### ISSUE TITLE
Auto disconnect after timeout

### ISSUE THREAD

**Issue by GadiRiversideFM** [centrifugal/centrifuge-js#248]
Hi!
is there a disconnection event after some amount of timeout when socket is trying to reconnect? it seems it tries to reconnect forever if network goes down. is it configurable? let's say if the socket fails to connect after 30 secs, disconnect or close the client.

**Comment by FZambia** [comment]
Sorry, not `disconnected` event - but after `connecting` event. See https://centrifugal.dev/docs/transports/client_api#client-connection-states

**Comment by FZambia** [comment]
@GadiRiversideFM hello, were you able to try this?

**Comment by GadiRiversideFM** [comment]
@FZambia sorry for late response, I eventually created a timer myself for disconnection.I agree with what you said on that infinite retries
