### ISSUE TITLE
getToken cb for connection token does not fire

### ISSUE THREAD

**Issue by GadiRiversideFM** [centrifugal/centrifuge-js#256]
**Describtion**
I'm using the `Centrifuge` class option `getToken`  to retrieve new token every X timeout to fetch a new token.
It seems like it's **not** firing if the token expires after 1 hour. It did fire on another centrifuge server env.not really sure it relates to timeout...
Is there any config or some server side config missing? something else?

**To Reproduce**
1. connect to a session that expects a connection token
2. pass a `getToken` callback to the `Centrifuge` class option and a valid token 
`new Centrifuge("endpoint", {token: "validToken", getToken: Function})`
4. make sure token expires after one hour
5. callback doesn't fire

**Expected behavior**
callback should fire

**Versions**
 -  MacOS Version 13.0.1 (22A400)
 -  chrome 115
 - Centrifuge client version  4.0.1

**Additional context**
example token: `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYTBlYzIwYS1jZWIwLTQ3OTktOWRiNy01ODQ0MGRmZWM4NTQiLCJpYXQiOjE2OTUxNDI4MzIsImV4cCI6MTY5NTE0NjQzMn0.aHVFC5MolGDaAO3AMct6mzjDUWN7kbccpge1ayRn6cE`

**Comment by GadiRiversideFM** [comment]
Update: server config flag `client_insecure` was on `true`

**Comment by FZambia** [comment]
Thanks for sharing the root cause!
