### ISSUE TITLE
malformed transport configuration

### ISSUE THREAD

**Issue by hardsmile98** [centrifugal/centrifuge-js#258]
**malformed transport configuration**
I'm getting an error like this: "malformed transport configuration"

**To Reproduce**
1. Start centrifugo
2. See error

**Expected behavior**
Correct behavior without errors

**Screens**
![Снимок экрана (582)](https://github.com/centrifugal/centrifuge-js/assets/34037597/29d22d36-78fc-4b06-bf28-a75679e8add5)

**Versions**
- centifugo-js v5.0.0
- Chrome 117.0.5938.132

**Comment by FZambia** [comment]
Most probably you have sth like `Array.prototype.??? = ` in your project, but nevertheless the fix is needed in `centrifuge-js`. Thanks for PR
