### ISSUE TITLE
Odd "already subscribed" subscription failure due to getToken race condition

### ISSUE THREAD

**Issue by Mr-Wallet** [centrifugal/centrifuge-js#265]
**Describe the bug**
Since `getToken` is an async function, it's possible to call `centrifuge.newSubscription`/`sub.subscribe` while `centrifuge.connect` is waiting to receive a token. (My use case is that the token _and_ channel can change as a result of a user login event.)

If this happens, `connect` will then attempt to subscribe on all of its subscriptions, and since `sub.subscribe` was already called, this will cause a 105 "already subscribed" error. Worst of all, this error calls `sub._setUnsubscribed` so that the "already subscribed" error results in not actually being "already subscribed"!

**To Reproduce**
1. Define a `getToken` which calls `sub = centrifuge.newSubscription('channel'); sub.subscribe();` (to guarantee that these calls occur while getToken is running - but a more complicated setup with timeouts should have the same effect).
2. Construct a centrifuge instance with the `getToken` and call `centrifuge.connect()`.

**Expected behavior**
- For a library leaning toward resilience and not having to worry much about connection state if I don't want to, I'm a little surprised that centrifuge cares if I'm "already subscribed" or not. I would expect a warning at most, and certainly not _unsubscribing_ as a response to multiple calls to `sub.subscribe()`. That's clearly the opposite of what we want, so if there's no problem with the existing subscription, why shut it down?
- The docs heavily imply that calling `sub.subscribe()` is a manual process (note that Quick Start calls it before calling `connect()`), so this was tricky for me to debug. It was weird that my sub in a "subscribing" state got another attempted subscription just because I called `centrifuge.connect()`. I'm sure it makes perfect sense on an implementation level but so far I can't find in the README where I could get any hint that `_sendSubscribeCommands` is going to be called upon transport initialization.

I'm not sure what the solution is but the two points above combine to create an awkward situation that feels like this was an unintentional race condition. For now it seems that I will need to create a strictly-ordered process of e.g. `disconnect -> unsub -> sub -> reconnect`, instead of handling the connection and subscriptions independently (i.e. asynchronously).

**Versions**
 - Electron 27 (main "non-browser" process)
 - Centrifuge client version 5.0.1

**Comment by FZambia** [comment]
Hello @Mr-Wallet 

Looking at reproducing steps you are trying to create new Subscription in getToken every time getToken called:

```javascript
const centrifuge = new Centrifuge(
  address,
  {
    getToken: function (ctx) {
      var sub = centrifuge.newSubscription(channel, {});
      sub.subscribe();
      return getToken('/centrifuge/refresh', ctx);
    },
```

This is invalid usage of `centrifuge-js`. And this code throws: `Subscription to the channel chat:index already exists` on second getToken invokation - which is expected to happen.

The error from server `105 "already subscribed"` is not reproduced here for me.

In general `105 "already subscribed"` signals about some SDK bug or SDK misusing, that's why we keep it. Probably you have some complex or just unusual scenario we missed which results into such race – but I need proper steps to reproduce to help.

> My use case is that the token and channel can change as a result of a user login event.

I suppose you better to provide steps to reproduce which reflect your real app and reproduce the issue clearly

**Comment by Mr-Wallet** [comment]
Sorry, I was trying to give you some minimal runnable code that would cause a repro. As it is a race condition, there is no 100% reliable repro without some sort of contrivance. As I hinted in the original post, a more complicated but realistic repro is to have `getToken` await a promise which does not resolve for a while, and then initialize the subscription during that time window:

```
getToken: function () {
  return new Promise((resolve) => { setTimeout(resolve, 4000); }).then(() => 'token');
}

// after creating centrifuge:
setTimeout(() => {
  const sub = centrifuge.newSubscription('channel');
  sub.subscribe();
}, 1000);

centrifuge.connect();
```

When the user changes, I need to update both the token and the channel. To update the channel I use `centrifuge.removeSubscription`* and remove all the listeners from the sub, then create a new subscription. To update the token I use `centrifuge.disconnect` and `centrifuge.connect`, relying on `getToken`. I have already guaranteed that the old channel is unsubscribed before `connect` (the old channel is forbidden to the new token). However, that's not enough, I also need to make sure that the the new subscription is created _before_ or _after_ `connect`, because if it happens during `getToken` then I'm going to hit the "already subscribed" error and it's going to unsubscribe me.

-----

\* `centrifuge.removeSubscription` also calls `sub.unsubscribe` - the sub doesn't need to be in an unsubscribed state already, in spite of what the README says. Also, the opposite is not true: `addSubscription` does not call `sub.subscribe`. The whole situation with `add/removeSubscription` basically requires going to the original source and reading the implementation in order to use them properly, which is not ideal.

**Comment by FZambia** [comment]
> When the user changes, I need to update both the token and the channel. To update the channel I use centrifuge.removeSubscription* and remove all the listeners from the sub, then create a new subscription. To update the token I use centrifuge.disconnect and centrifuge.connect, relying on getToken. I have already guaranteed that the old channel is unsubscribed before connect (the old channel is forbidden to the new token). However, that's not enough, I also need to make sure that the the new subscription is created before or after connect, because if it happens during getToken then I'm going to hit the "already subscribed" error and it's going to unsubscribe me.

Could you please provide a full reproducer as a code?

**Comment by Mr-Wallet** [comment]
Something like this should do it:

```js
// Node.js
const { Centrifuge } = require('centrifuge');
const WebSocket = require('ws');

// Replace these values with ones for a real backend
const socketUrl = 'wss://example.com';
const channel = 'channel';
const token = 'token';

(async function() {  
  const c = new Centrifuge(socketUrl, { websocket: WebSocket, getToken: async function() {
    // simulate a slow getToken
    return new Promise((resolve) => { setTimeout(resolve, 4000); }).then(() => token);
  }
  
  // A separate promise "thread" subscribes to a channel while getToken is still running
  setTimeout(() => { c.newSubscription(channel).subscribe(); }, 1000);
  
  c.connect();
  await c.ready();
})();
```

It calls `self._sendSubscribeCommands(true, false)` at [centrifuge.ts#L820](https://github.com/centrifugal/centrifuge-js/blob/master/src/centrifuge.ts#L820). This causes `c` to look at its internal list of subscriptions and attempt to subscribe to them all, which fails on the existing subscription [here](https://github.com/centrifugal/centrifuge-js/blob/master/src/subscription.ts#L392) because it's already subscribed. And then, most confusingly of all, it responds to "already subscribed" by _unsubscribing_ [here](https://github.com/centrifugal/centrifuge-js/blob/master/src/subscription.ts#L518) because 105 isn't treated in any special way. (That last part was really hard to figure out because it's not clear why `"please subscribe me" -> "error: already subscribed"` should be handled by dismantling the existing subscription; that's almost definitely not the situation that the programmer wants to end up with.)

So far I've only reproduced during `connect()` but I'm a little worried about whether it will also happen during automatic reconnection with flaky internet, or automatic token renewal. It will be difficult to guarantee that channel subscriptions can _never_ happen while these events are being processed, so if the bug is present there as well then I will have to do my own state management to prevent errors.

**Comment by FZambia** [comment]
Are you sure you provided a full code which reproduces `already subscribed` error?

It just connects and subscribes once. I just ran it to be sure and it works fine for me. While you are describing sth more complex which involves second subscription.

**Comment by FZambia** [comment]
If that was the full code – is it possible that your token has [channels](https://centrifugal.dev/docs/server/authentication#channels) claim and it has the same channel in it as the one you are using on client side to subscribe? So that you are using server-side subscriptions and also trying to subscribe on the same channel from the client side?

**Comment by Mr-Wallet** [comment]
Yes, that's definitely it... thank you!

The token issuing is being done by another team member so I wasn't aware of the claims in the token; additionally, I double-checked the README and the docs at your link as well as [here](https://centrifugal.dev/docs/transports/client_api#client-connection-token) and didn't see any evidence that the JWT claims other than `exp` would _automatically_ affect anything on the client side. The section on [server-side subscriptions](https://centrifugal.dev/docs/transports/client_api#server-side-subscriptions) does not explain that they will arise automatically from claims in the JWT.

OK, enough complaining about the docs. I'm going to confer with my team and suggest that we should consider moving away from the JWT channel claim for better client-side control, as the documentation encourages.

As far as actionable requests (beyond documentation), I'm going to continue to insist that, trying to subscribe to a channel a 2nd time should never be handled by both losing the existing subscription and abandoning the new one as well. Besides that I think you've solved my confusion. 🙏

**Comment by FZambia** [comment]
Nice! 👍 

As some action from here I just improved docs in https://github.com/centrifugal/centrifugal.dev/commit/cc189cc6fd234940f60b1b6e7ee90a979c02a006

`already subscribed` is required as it signals about SDK bugs or SDK/Centrifugo misuse. Like this case for instance. There are reasons why we can't handle this error automatically – this comes from the subscription semantics and its expected behaviour. If we handle such cases somehow - I think it could result into more non-obvious problems later, not during development/integration stage. So I believe strictness here is necessary at this point.

> we're intended perhaps to use a separate token for each subscription, separate from the global token attached to centrifuge, and those subscription tokens give the grants for individual channels. Let me know if we're on the right track, and thanks again.

Subscription tokens provide granular and quite efficient way to work with channel permissions in Centrifugo – so usually it's just fine to use them for channels which require access control. Always recommend to read [101 ways to subscribe user on a personal channel in Centrifugo](https://centrifugal.dev/blog/2022/07/29/101-way-to-subscribe).

**Comment by Mr-Wallet** [comment]
Thanks for the advice, and also for the doc updates; I hope those will help others getting started in the future. We will review carefully, but for now it seems that for granular permissions we will try to have each channel on a different subscription, each with a different `getToken`, calling a different route for each channel's token. This does start to make apparent the use case for the `caps` claim on Centrifugo PRO. 😅 

I believe you can close this issue. Your responsiveness has been much appreciated!

**Comment by Mr-Wallet** [comment]
P.S. A bit of a tangent, but `ready`/connected is a little less of a guarantee than I expected. If I wait for both centrifuge and a subscription to be `ready`, then immediately ping my back-end to send something over the channel, the sub's publication handler consistently fails to trigger. But if I wait for `ready` on everything _and_ another 100ms, I consistently get the message. So `ready` is not merely "not ready", it's "still not going to be ready in the time it takes to round-trip with the backend". I would expect to almost always get a message that was sent from the server after the "ready" event fired. Is this potentially a separate bug, or am I misunderstanding something again?

**Comment by FZambia** [comment]
I don't know without concrete reproducer - probably a bug, probably not. Just show reproducing code, write the concrete error you get - and there won't be any uncertainty

**Comment by Mr-Wallet** [comment]
There's no error generated, I just don't get a message. This is the basic structure:

```
// centrifuge has 1 sub in a 'subscribing' state. This sub has a getToken which has to wait for a GET from a REST API.
centrifuge.connect();
await centrifuge.ready();

// NOTE the sub is not finished subscribing at this point, which was unintuitive IMO. So we wait for the sub here:
await Promise.all(Object.values(centrifuge.subscriptions()).map(sub => sub.ready()));

// The sub's publication callback never fires for this message, even after 10 runs:
post_to_REST_API_which_sends_message_on_sub('message one');

// However, this one works perfectly every time by delaying another 100ms:
setTimeout(() => post_to_REST_API_which_sends_message_on_sub('message two'), 100);
```

**Comment by FZambia** [comment]
> There's no error generated, I just don't get a message. This is the basic structure:

I need to check, this should work if I understood the logic right. I.e. from what I am reading above:

* you are subscribing to channel and waiting for subscription to be ready
* you are trying to publish message to channel using a call to server API which calls Centrifugo server API

When subscription is ready - server already has client in subscription map, so publishing should work

**Comment by Mr-Wallet** [comment]
Yes, you've got it. I create a sub, then connect (with `ws` as the transport), wait for centrifugo-js to be `ready()`, then wait for the sub to be `ready()`, then on the same JS thread, only after all of that, I have 2 scenarios:
1. immediately POST to a REST API which triggers a message for the subscription.
2. Wait 100ms, _then_ do the POST

Under scenario 1, I never get the message (and there's no errors). Under scenario 2, I always get the message. So basically right now I'm making it very clear to the team, "Please don't do anything immediately at startup which is going to rely on getting a message, just because you waited for the centrifugo system to start-up doesn't mean you're getting messages yet. Instead make sure your REST call is responding directly with the information you need." This is a workable policy, but it would be ideal if waiting for things to be ready guaranteed that they were _actually_ ready (in the absence of problems, of course).
