### ISSUE TITLE
Upgrading es6-promise dependency

### ISSUE THREAD

**Issue by JeanCarriere** [centrifugal/centrifuge-js#28]
When using centrifuge-js within an app having a dependency on es6-promise, it seems there is a conflict due to the version of this library.
Would it be possible to update to es6-promise > 4 ?

**Comment by FZambia** [comment]
@JeanCarriere just published 1.4.5 with this change, please check it out

**Comment by FZambia** [comment]
@JeanCarriere any update?

**Comment by JeanCarriere** [comment]
Yes no problem, it works fine. Tks.
