### ISSUE TITLE
Not available error after Successful connection

### ISSUE THREAD

**Issue by BrianMwas** [centrifugal/centrifuge-js#284]
**Describe the bug**
I have been trying to connect to the centrifugal server but am always getting the not available code 108 error. When I check with the server it does record subscribing and shows me the channel info but that's it,  On the admin panel, I do not see the available connections, they are all empty or 0

**To Reproduce**
1. Create a golang centrifuge server
2. Create a centrifuge client server with React and type script 
3. Connect server and client using Websocket transport
4. Try and publish a message to the client

**Expected behavior**
I need to see the messages showing somewhere or at least able to see the admin panel show connections. After I publish since its giving me a successful response when I try to publish using an API
Here is my config, no errors on the server side just the error code on the client

**Screenshots**

**Versions**
 - Centrifuge 5.2
 - Chrome Version 125.0.6422.60 (Official Build) (arm64)
 - Centrifuge client version 5.2.0-beta.1
 - Server version v0.32.2

**Additional context**

**Comment by BrianMwas** [comment]
<img width="1440" alt="Screenshot 2024-05-21 at 17 17 56" src="https://github.com/centrifugal/centrifuge-js/assets/42889128/91b063cb-cb7e-41a5-a76a-8dddfa2928f9">

**Comment by BrianMwas** [comment]
<img width="1440" alt="Screenshot 2024-05-21 at 17 23 28" src="https://github.com/centrifugal/centrifuge-js/assets/42889128/f3368954-a47e-4afb-b7c9-988017cd55c5">

**Comment by FZambia** [comment]
Hello @BrianMwas 

Usually you are not supposed to use https://github.com/centrifugal/centrifuge and https://github.com/centrifugal/centrifugo in one project, that's possible but requires proper understanding of boundaries between them. There are no guidelines for combining them at this point.

I do not see enough information here to help exactly, most probably you have not defined `OnPublish` callback in server code where you are using Centrifuge library.

Regarding connections – I guess you now have separate instances of server (Centrifugo and Centrifuge-based) which do not know nothing about each other.

**Comment by BrianMwas** [comment]
Its okay, I realized I was using my server without a port instead of using the centrifugal one,
