### ISSUE TITLE
Issue with Unsubscribe Not Resetting presenceStats num_clients in Centrifugo.js

### ISSUE THREAD

**Issue by bethlehem-dagnachew** [centrifugal/centrifuge-js#286]
Describe the bug

When using the unsubscribe() method in Centrifugo.js, the presence status does not reset. Specifically, the number of clients keeps increasing even after unsubscribing and subscribing again. Additionally, when I check the subscription state before subscribing to a channel, it always starts as "unsubscribed" upon page refresh, even if the client is already subscribed to the channel. This behavior causes the number of clients to increase continuously, as the client is repeatedly subscribed without resetting the previous subscription. As a result of this issue, when a user receives a message, Centrifugo sends the message based on the inflated num_clients count in the channel, causing duplicate notifications to be sent to the user

To Reproduce

1. Connect with the server and Create a subscription to a channel using Centrifugo.js.
2. Unsubscribe from the channel using the unsubscribe() method.
3. Subscribe to the the channel.

Additionally, when the server connects and I observe the subscription state, starts as "unsubscribed". Even though the subscription state starts as "unsubscribed", the num_clients value increases with each page reload or navigation when the client connect and subscribe to the channel. The unsubscribe() method does not reset the num_clients count, and I have to perform a hard refresh to reset it.

Expected behavior
The number of clients in the presence status should reset correctly after unsubscribing and subscribing again. The client count should accurately reflect the current number of subscribed clients. Additionally, the subscription state should correctly reflect the actual subscription status upon page refresh, preventing redundant subscriptions and inaccurate client counts.

Screenshots

![Screen Shot 2024-06-12 at 9 10 24 PM](https://github.com/centrifugal/centrifuge-js/assets/52574965/55448b6e-0dda-4e89-9a9c-df1d9fa60a31)

When users receive messages from the server, the messages are sent based on the num_clients count. If num_clients is 6, six identical messages are sent to the channel.

<img width="793" alt="Screen Shot 2024-06-12 at 9 11 35 PM" src="https://github.com/centrifugal/centrifuge-js/assets/52574965/dcf5b9ab-ae9a-4f56-ab5f-1750bec6ce6b">

Versions

OS: MacOS
Browser or environment with version: Mozilla firefox, Node 18.16.1, Vue 3
Centrifuge client version: 5.0.1
Server version: 5.4

Additional context
The presence status incorrectly increases the client count, leading to inaccurate presence data and redundant messages and notifications sent to the client, which is critical for applications relying on real-time presence information. When the subscription state starts as "unsubscribed" by default, it fails to decrease or reset the number of clients, causing the client count to increase with each page refresh or navigation.

**Comment by FZambia** [comment]
Hello @bethlehem-dagnachew 

I just checked - I am not able to reproduce this. Probably you are using the library in the wrong way. Or I am missing sth.

1. First of all, try latest version of centrifuge-js
2. Which transport you are using - WebSocket?
3. Finally, please provide a standalone minimal code which reproduces a problem – so I can run it and see the issue. Please, without using Vue – since the issue may be due to Vue specifics. Looking at your description it should be simple to provide a self-contained snippet.

**Comment by bethlehem-dagnachew** [comment]
Hello @FZambia  Thank you for your response 

1. I'm using the latest centrifugo-js: version [v5.4.0] on the server-side and version [v5.2.0] on the client-side, both of which are the latest versions available via npm.
2. Yes, I'm using WebSocket.
3. I've uploaded my JS code below. Maybe I missed something. I appreciate your help.

```my centrifugo.js File 

import { Centrifuge } from "centrifuge";
import { useUtilities } from "@/services/utilities.js";
import { useStore } from "vuex";
import { ref } from "vue";

export const useCentrifuge = () => {
  const { getCentrifugePath } = useUtilities();
  const centrifugePath = getCentrifugePath();

  const connectionStatus = ref("disconnected");
  const subStatus = ref("");

  const store = useStore();

  const mqtoken2 = store.getters["login/getMqToken2"]();
  const mquser = store.getters["login/getMqUser"]();

  const transports = [
    {
      transport: "websocket",
      endpoint: centrifugePath,
    },
  ];

  const centrifuge = new Centrifuge(transports, {
    token: mqtoken2,
  });

  const createSubscription = (channel) => {
    let sub = centrifuge.getSubscription(channel);
    if (!sub) {
      try {
        sub = centrifuge.newSubscription(channel);
      } catch (error) {
        console.error("Failed to create subscription", error);
        return;
      }
    }

    subStatus.value = sub.state;

    sub.on("unsubscribed", function (context) {
      console.log("unsubscribed", context.channel);
    });
    sub.on("subscribing", function (context) {
      console.log("subscribing", context.channel);
    });
    sub.on("subscribed", function (context) {
      console.log("subscribed", context.channel);
      subStatus.value = sub.state;
    });
    sub.on("publication", function (context) {
      console.log("publication", context.channel);
      subStatus.value = sub.state;

      const message = context.data;
      console.log("Received message:", message);
    });
    sub.on("error", function (context) {
      console.log("subscription error", context);
    });

    const centrifugeSubscriptions = centrifuge.subscriptions();
    if (centrifugeSubscriptions) {
      console.log(
        "🚀 checking subscription state,:",
        centrifugeSubscriptions[channel]?.state,
        channel
      );

      if (centrifugeSubscriptions[channel]?.state === "subscribed") {
        console.log("Already subscribed to channel:", channel);
        sub.unsubscribe().then(() => sub.subscribe());
      } else {
        sub.subscribe();
      }
    }
  };

  const connectToCentrifuge = () => {
    centrifuge.on("connecting", () => {
      console.log("connecting to Centrifuge");
      connectionStatus.value = centrifuge.state;
      console.log("connectionStatus.value....", connectionStatus.value);
    });

    centrifuge.on("connected", () => {
      console.log("Connected to Centrifuge");
      connectionStatus.value = centrifuge.state;
      console.log("connectionStatus.value....", connectionStatus.value);

      createSubscription(`ping`);
      createSubscription(`chat#${mquser}`);
    });

    centrifuge.on("error", (err) => {
      console.error("Centrifuge error:", err);
    });

    centrifuge.on("disconnected", () => {
      console.log("Disconnected from Centrifuge");
      connectionStatus.value = centrifuge.status;
      console.log("connectionStatus.value...", connectionStatus.value);
      store.dispatch(
        "traktel/updateCentrifugoConnectionStatus",
        centrifuge.status
      );
    });

    centrifuge.connect();
  };

  const connectToMessageServer = async () => {
    centrifuge.disconnect();
    connectToCentrifuge();

    centrifuge.on("error", (err) => {
      console.error("Centrifuge error:", err);
    });
  };

  return {
    connectionStatus,
    subStatus,
    connectToCentrifuge,
    connectToMessageServer,
  };
};
```

**Comment by FZambia** [comment]
I don't think [sub.unsubscribe()](https://github.com/centrifugal/centrifuge-js/blob/a5384ce69429053a7a3217072574ee331b310eb8/src/subscription.ts#L119) returns promise at this point to do the following:

```
sub.unsubscribe().then(() => sub.subscribe());
```

My guess is that you have an unhandled exception which results into issues.

Another thing is that you are adding event listeners to Subscription object on every reconnect (in `connected` event handler for example) – which will result into duplicate event invocations. You need to create subscriptions and event handlers outside event handlers or do proper event listeners cleanup.

P.S. But in general, I think making `sub.unsubscribe` to return a Promise could be a good thing

**Comment by bethlehem-dagnachew** [comment]
Thank you @FZambia for your recommendation. I also implement sub.unsubscribe to return a promise. but it didn't work. I will try the event listener recommendation.

**Comment by bethlehem-dagnachew** [comment]
We previously used an older version of centrifugo, and it worked fine. Now we're truing to implement the latest version for our new app, but we're encountering issues with unsubscribe not working as expected.

**Comment by FZambia** [comment]
> Additionally, the subscription state begins as 'unsubscribed' when connecting to the server. When I log the subscription before calling sub.subscribe(), it initially shows as 'unsubscribed' always even if there is a subscription. However, when i expand the object, it indicates 'subscribed', but the subscribe.state indicate 'unsubscribed' before expanding the object.

It's a normal behavior, I do not understand the question TBH. It works as described here: https://centrifugal.dev/docs/transports/client_api#subscription-states

**Comment by bethlehem-dagnachew** [comment]
I mean if the state starts from unsubscribe the num_client should reset right? All I want is to avoid increasing the num_client with the same user Id. For that I'm trying to use sub.unsubscribe ().

**Comment by FZambia** [comment]
I already provided recommendations above - I think you are using unsubscribe as promise while it's not a promise at this point, and this leads to issues you have. Refactor your code, also avoid setting event listeners many times.

If you will still have issues after that, post the reproducer here and I'll take a look again. If you need more help you need to provide code which I can run - without Vue dependencies and third-party imports.
