### ISSUE TITLE
Lack of Documentation & Examples

### ISSUE THREAD

**Issue by deresegetachew** [centrifugal/centrifuge-js#31]
As awesome as centrifugo is I believe documentation is lacking. I was wondering if there was an example with JS client implementing a private channel using the respective Node.JS backend.
Almost all examples are using Insecure mode when it comes to JS and that is not helpful when we want to take it to production.  This is the only documentation available https://fzambia.gitbooks.io/centrifugal/content/clients/javascript.html#private-channels and this https://fzambia.gitbooks.io/centrifugal/content/mixed/private_channels.html  ; but both are lacking JS and Node.js Examples. I also believe a Diagram will also be helpful to explain private channel life cycle.

**Comment by FZambia** [comment]
@deresegetachew thanks for pointing on this, I'd be happy if we have more examples of course - but  it's sometimes hard to find a time for this so I appreciate any help with Centrifugo ecosystem.

Regarding to diagram: our private channel subscriptions are very similar to [pusher.com analogue](https://pusher.com/docs/authenticating_users#authentication_process) - with some differences though but life cycle is pretty much the same, will try to draw it.

**Comment by FZambia** [comment]
And regarding to non-insecure example - now we have only Django example which receives connection credentials with backend - [here is js code](https://github.com/centrifugal/examples/blob/master/django/core/templates/core/index.html) - maybe it will be helpful

**Comment by deresegetachew** [comment]
I will see what i can do with a full-fledged end to end example. If we are to grow this awesomeness we need examples. do drop me a line or two and i will share with you a google docs to collaborate on. deresegetachew@gmail.com is my email.

**Comment by FZambia** [comment]
We now have [NodeJS example](https://github.com/centrifugal/examples/tree/master/nodejs) contributed by @synw
