### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by johndoejdg** [centrifugal/centrifuge-js#32]
Are you have plans migrate to TypeScript? Would be great to have autocomplete and type checking in IDE.

**Comment by FZambia** [comment]
@johndoejdg not at moment I think - the main reason is that I am not a Javascript guy and I had no TypeScript experience before and have no plans learning it, so for me it will be a dive into new technology – hard to find time for it. Actually even if someone create pull request with TypeScript migration it will be hard for me to maintain new code base – so I prefer keeping code in plain old Javascript.

**Comment by Inpassor** [comment]
@johndoejdg have a look at #53
