### ISSUE TITLE
Need callback for error in connection

### ISSUE THREAD

**Issue by bubooon** [centrifugal/centrifuge-js#33]
I want detect, if JS client can't connect to centrifugo, but i can't do this. I have just error in console
`WebSocket connection to 'ws://domain.loc:8000/connection/websocket' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`
Can you add some event for it?

**Comment by FZambia** [comment]
@bubooon hello! Yeah, I think it's reasonable to have, could you describe why do you specifically need this btw?

**Comment by bubooon** [comment]
For example, I have an important functional in my application which depend on centrifuge . If suddenly the server of the centrifuge down, I want to show an adequate message for the user and not let him use this functionality, now it is impossible to do it, because i can't handle this error.

**Comment by FZambia** [comment]
Got it, thanks, will try to add during this weekend.

**Comment by FZambia** [comment]
@bubooon just found a time to play with your request and I wonder why not using existing `disconnect` event for your case:

```javascript
centrifuge.on('disconnect', function(ctx){
    console.log('Disconnected: ' + ctx.reason);
});
```

**Comment by bubooon** [comment]
@FZambia Because i connect and disconnect to centrifuge in app and i will get this event when i disconnect manually. Better have special event when you trying connect but get error, because server is not responsing.

**Comment by FZambia** [comment]
Hmm, it's not as easy as I initially thought. If using raw Websockets we can add callback to `onerror` event and it will be called every time client tries to reconnect to Centrifugo and server unavailable. But the hard part here is SockJS which does not use `onerror` event - it tries to create connection using possible transports - I need a time to investigate more.

**Comment by bubooon** [comment]
And one more thing, i have disconnect event only one time, if i will disconnect manually and try to connect again i have not this event more, because client trying reconnect.

**Comment by bubooon** [comment]
Any news?

**Comment by FZambia** [comment]
@bubooon I am sorry for a delay - the reason why I have not just added this yet is SockJS which has no `onerror` event. But I have not found time to investigate this case more - will try to look at this ASAP.

**Comment by FZambia** [comment]
@bubooon please look in [on_transport_close](https://github.com/centrifugal/centrifuge-js/blob/on_transport_close/centrifuge.js) branch and [this comparison](https://github.com/centrifugal/centrifuge-js/compare/on_transport_close) - I added `onTransportClose` callback which will be executed every time there is problem with connection (both raw Websocket and SockJS). There is also build with these changes in that branch so you can test in in your development environment. Does this help to solve your case?

**Comment by FZambia** [comment]
@bubooon hi, I merged changes above into master, please reopen if it does not work for you and you still need a solution.

**Comment by bubooon** [comment]
@FZambia, hi, sorry for a long response, but this is not solve my issue. I need catch event, for example, when i set bad port or Centrifuge server is down. Now in this case i have error:
`WebSocket connection to 'ws://127.0.0.1:8001/connection/websocket' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`
And i have this message every 5-10 seconds.

I won't just handle this case.
