### ISSUE TITLE
authEndpoint 401 responses

### ISSUE THREAD

**Issue by flc** [centrifugal/centrifuge-js#34]
is there a way to detect 401 Unathorized responses from the authEndpoint? that would be useful in the case when the user's current access token expires and a new one has to be acquired. also, is there a way to make the centrifugo client retry the authEndpoint and the subscription attempt after that?

**Comment by FZambia** [comment]
Hello, currently it all happens behind the scene so no way to hook into.

**Comment by FZambia** [comment]
I think we can add sth like:

```
new Centrifuge({
    ...,
    onRefresh: function() { ... }
})
```

This function will be called as soon as it's time to refresh token, centrifuge-js will call this func if provided and won't try to do anything automatically - so it's up to library user to decide how to get credentials, handle errors etc (i.e. send AJAX request manually) - this seems flexible enough if someone wants more control in refreshing workflow. @flc what do you think?

**Comment by flc** [comment]
In the meantime I've found a workaround. Every time the frontend acquires a new access token I update `authHeaders` with a `configure` call. Since every view in my spa requires an API call (which refreshes the acccess token automatically if needed) and I call `subscribe` only after that, it seems to solve the problem for now.

I'm not sure how `onRefresh` would help. When would it be called exactly? Handling everything manually related to subscribing private channels doesn't sound to good to be honest.

Btw when calling subscribe it's possible to define an error event. I think that is enough since I can catch `authorization request failed` errors, refresh the token and attempt the subscription again. But in case of this type of error the status code and the whole response body would probably be helpful instead of just `error: "authorization request failed"` because then I could exactly decide if the error happened because of an expired/invalid access token.

**Comment by FZambia** [comment]
I am sorry, for some reason I was thinking about controlling refresh mechanism - can't explain why:) So ignore my last comment.

**Comment by FZambia** [comment]
@flc addidional logic can now be implemented using custom `onAuth` callback function introduced in 1.4.7
