### ISSUE TITLE
After a long disconnect, the messages are received 2 times

### ISSUE THREAD

**Issue by JeanCarriere** [centrifugal/centrifuge-js#37]
![image](https://user-images.githubusercontent.com/2640544/28314414-cc82392c-6bba-11e7-8674-26a38c6844e8.png)
It seems that after a long disconnection time, when the connection is reestablished, the onmessage function is called 2 times.
I use sockJS

**Comment by FZambia** [comment]
Hello, please show a code snippet to reproduce an issue

**Comment by JeanCarriere** [comment]
Hard to reproduce systematically.
But it seems that it could be due to https://github.com/sockjs/sockjs-client/issues/334
I'm closing this issue and see if the fix from sockjs solves this issue.

**Comment by FZambia** [comment]
OK waiting for info from you
