### ISSUE TITLE
'debug' parameter is not working in Chrome

### ISSUE THREAD

**Issue by Orabig** [centrifugal/centrifuge-js#38]
I tested the same JS code and compared with 4 browsers : 
Internet Explorer (11.540)
Microsoft Edge (40.15063)
Firefox (54.0.1)
Chrome (60.0.3112)

When using ```handle.connect( { ...., debug: true, ... } );``` I don't get any messages in the console in Chrome, while I got them correctly on Edge, IE and Firefox.

**Comment by FZambia** [comment]
Seems that it relates to log level selected in Chrome.. See this picture:
<img width="1439" alt="screen shot 2017-08-26 at 13 20 46" src="https://user-images.githubusercontent.com/1196565/29740546-8a94c1fe-8a61-11e7-8250-93eaf1dd1a38.png">
Take a look at Default levels and try to select `Verbose` - this theoretically can help to turn debug logs on.

**Comment by Orabig** [comment]
You're right, thanks. I didn't know about this parameter.
