### ISSUE TITLE
withCredentials support

### ISSUE THREAD

**Issue by a1martin** [centrifugal/centrifuge-js#39]
Hi,
There seems to be no option to specify that the token request to backend should be done with using option xhr.withCredentials=true.  Thus the request fails in CORS scenario.

**Comment by FZambia** [comment]
@a1martin thanks for an issue! If you have time and possibility to make pr - I'll be happy to accept it. Otherwise I'll add support for this as soon as I can.

**Comment by Inpassor** [comment]
#51

**Comment by FZambia** [comment]
Merged in master - it won't work for old browsers though.
