### ISSUE TITLE
Error WEBPACK_IMPORTED_MODULE_0_centrifuge__.a is not a constructor

### ISSUE THREAD

**Issue by pnvasko** [centrifugal/centrifuge-js#41]
Hey, i try use centrifuge with Vue2.
code like this: 
import Centrifuge from 'centrifuge'
var centrifuge = new Centrifuge({
  url: 'ws://localhost:8000/connection/websocket',
  user: '42',
  timestamp: '1509295885',
  token: '106a528f311bb413bded9523109e031c2023c83cdca097612b771b1c94243d51',
  transports: ['websocket']
})
console.log('Centrifuge: ', centrifuge)
export default ( 
  centrifuge
)
after compiling get in browser error: 
Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_0_centrifuge__.a is not a constructor
how i can fix it?
when use in .html work correct
p.s. install by npm

**Comment by FZambia** [comment]
Hello! Don't know an exact reason - have you googled this error? I found something similar [here](https://stackoverflow.com/questions/36388766/unexpected-uncaught-typeerror-xxx-is-not-a-constructor-errors-with-babel-and)

**Comment by pnvasko** [comment]
Yes, try it too - not Help...


понедельник, 30 октября 2017 г. пользователь Alexandr Emelin написал:

**Comment by FZambia** [comment]
Then please could you make a small example that helps to reproduce this?

**Comment by FZambia** [comment]
As far as I know now you can workaround this problem using:

```
import * as Centrifuge from 'centrifuge';
```

Please reopen if problem persists and you have more information to reproduce!
