### ISSUE TITLE
How to unsubscribe ; there is no exposed method to call unsubscribe manually

### ISSUE THREAD

**Issue by deresegetachew** [centrifugal/centrifuge-js#42]
need to implement `centrifugeProto.unSubscribe`

**Comment by deresegetachew** [comment]
need to implement `centrifugeProto.unSubscribe`

**Comment by FZambia** [comment]
@deresegetachew hello - have you tried to call [unsubscribe method of subscription object](https://fzambia.gitbooks.io/centrifugal/content/clients/javascript.html#unsubscribe-method-of-subscription)?

**Comment by FZambia** [comment]
@deresegetachew please reopen if still actual.
