### ISSUE TITLE
enhancement with RethnkDB

### ISSUE THREAD

**Issue by geomen888** [centrifugal/centrifuge-js#59]
I'm kindly ask U to add scaling with RethinkDB into Ur awesome Centrifuge. Thank U

**Comment by FZambia** [comment]
Hello, it's a hard work - maybe one day I'll integrate Centrifuge with RethinkDB, Tarantool or Nats. But 
can't do this at moment - not in current focus. For now if you describe why you need this and how you see implementation of this could help.

**Comment by geomen888** [comment]
Thanks Alexander for your promt feedback. My company is the www.autoenterprise.com.ua

As for now our team developing project similar with Uber.  But it's going to be free and monetization should be from target advertising. We also start to developing server based on Java, Python, Vertx with micro services. We already have some server on JavaScript we use socket.io there and rethinkDB but it works without micro services and obliviously- client applications IOS, Android. So, we planing to continue our developing with RethinkDB, and not intended to leave particular  DB and join  with Redis Sentinal, in case we have already a lot of work to do ahead ;-). Our new server we planing to upload to AWS- Amazon cloud service. I managed with another pub/sub services as  socketcluster - it's seems to me more complicated with worker/broker implementation, as for socket.io it's have not official vertx.io support yet in comparison with Ur more secure service. 

https://www.slant.co/versus/614/1442/~rethinkdb_vs_redis

So, I hope U will accept my/our team request with understanding.

Thank U


Kind Regards Eugene 



Sent from Mail.Ru app for iOS


Sunday, May 13, 2018, 13:31 +0300 from notifications@github.com  <notifications@github.com>:

**Comment by FZambia** [comment]
Closing as this is not related to centrifuge-js repo
