### ISSUE TITLE
in iOS WebView, App crash when stopPing execute.

### ISSUE THREAD

**Issue by markrookie** [centrifugal/centrifuge-js#60]
I checked it out, crash happened after executed clearTimeout(this._pongTimeout).

**Comment by FZambia** [comment]
Hello! Thanks! hmm, I don't see nothing bad in that code. Maybe this is sth iOS webview specific? Do you have thoughts on the root of problem?

**Comment by markrookie** [comment]
Yes, it is something iOS WebView specific. I suppose it is JavaScript's this scope produce some bad memory in iOS WebView.

By the way. This did reproduce every time

**Comment by FZambia** [comment]
Could you try version with commit cbbda0c4c3158d172e818039b1ab1c119a97607b? ([this](https://github.com/centrifugal/centrifuge-js/blob/cbbda0c4c3158d172e818039b1ab1c119a97607b/centrifuge.js)) - it's a shot in the dark... I have no iOS device to try this myself.

**Comment by FZambia** [comment]
Please reopen if the problem still reproduces with v2
