### ISSUE TITLE
Event listeners added with subscribe method are not removed in unsubscribe method

### ISSUE THREAD

**Issue by nmorel** [centrifugal/centrifuge-js#63]
The subscribe method takes event listeners in parameters and returns a subscription object.  
When calling unsubscribe on it, I expected the listeners to be removed as well.  
But if I subscribe on the same channel, the subscription object is reused and the previous listeners are still there.  

As a workaround, I call `removeAllListeners` on the subscription after the unsubscribe call.  
I also remove the subscription from the _subs property to avoid issue #62.  
It works because my app does not have multiple subscription on a same channel at same time.

**Comment by FZambia** [comment]
Hello @nmorel . This looks the same as #54 

If not could you show some code demonstrating a problem?

**Comment by nmorel** [comment]
Yes, you're right, it's the same issue.  
Is there a reason the subscription is kept after an unsubscribe ?

**Comment by FZambia** [comment]
Keeping subscription object alive helps to resubscribe after reconnect (because after disconnect all subscriptions go to unsubscribed state). And another reason is that developer can only set event handlers once when first time subscribing and then do subscribe/unsubscribe calls on subscription object without need to set event handlers again.

Probably there is a better way to organize things - maybe you have ideas.

**Comment by FZambia** [comment]
Should we close this?

**Comment by FZambia** [comment]
Will appreciate help with documentation.

Maybe we should only call `removeAllListeners` in `unsubscribe` method of Centrifuge object. And leave listeners when calling unsubscribe on subscription. Looks like this is what users expect to happen. What do you think about this?

**Comment by FZambia** [comment]
I am currently trying to release Centrifugo v2 so hard to do side tasks, I agree that this is not obvious topic that should be documented – will try to document this at some point in future.

**Comment by FZambia** [comment]
Finally extended [unsubscribe docs a bit](https://github.com/centrifugal/centrifuge-js#unsubscribe-method-of-subscription).
