### ISSUE TITLE
`user` parameter is missing

### ISSUE THREAD

**Issue by artuska** [centrifugal/centrifuge-js#75]
There was the `user` parameter in `v1` config — where it is now in `v2`?

**Comment by artuska** [comment]
Now i reverted back to `v1` and i see:

```
["{\"method\":\"connect\",\"params\":{\"user\":\"uuid_2da2066252d64452ae2947e1ad94fb26\",\"info\":\"\",\"timestamp\":\"1549021818\",\"token\":\"2bcc4aa81e4a5b5788ec34bb0047e2b4c0c7bae4f561b42442e38d60d39579b8\"},\"uid\":\"1\"}"]
```

**Comment by artuska** [comment]
So, how do i include `user` and `timestamp` in `v2`?

**Comment by FZambia** [comment]
@artuska hello, user should now be included into JWT as `sub` claim. You on send JWT to Centrifugo without any other params. See https://centrifugal.github.io/centrifugo/server/authentication/
