### ISSUE TITLE
Race condition when trying to authenticate private channels

### ISSUE THREAD

**Issue by xAockd** [centrifugal/centrifuge-js#76]
Step to reproduce:
1. simulate long running subscription response on app backend
2. restart centrifugo while the subscription is running

Response:
error in reply client=aaa32115-f0e6-4049-84f7-92f2a75ac4c3 command="id:55 method:SUBSCRIBE params:"{"channel":"$privte.channel","token":"token"}" " error="103: permission denied" reply="id:55 error:<code:103 message:"permission denied" > " user=3389

Additional technical details:
If long-running subscription only for the first request we receive another error

error in reply client=aaa32115-f0e6-4049-84f7-92f2a75ac4c3 command="id:55 method:SUBSCRIBE params:"{"channel":"$privte.channel","token":"token"}" " error="105: "already subscribed" reply="id:55 error:<code:105 message:"already subscribed" > " user=3389

**Comment by FZambia** [comment]
Will try to make release later today

**Comment by xAockd** [comment]
Thanks. Really waiting for the fix.

**Comment by FZambia** [comment]
just released 2.1.2, please check it out
