### ISSUE TITLE
Centrifugo V2 + centrifuge-js GET https://my.site/connection/sockjs/info?t=... 404

### ISSUE THREAD

**Issue by chelkaz** [centrifugal/centrifuge-js#79]
I use Centrifugo V2
curl http://localhost:8000/connection/sockjs/ = Welcome to SockJS!
I GET https://my.site/connection/sockjs/info?t=... 404
How i can TEST connect?
My NGINX:
`upstream centrifugo {
    # Enumerate all the Tornado servers here
    #sticky;
    ip_hash;
    server 127.0.0.1:8000;
    #server 127.0.0.1:8001;
}

map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}
server {
  listen 80;
  listen 443 ssl http2;
  ssl_certificate /usr/local/nginx/conf/ssl/my.site.crt;
  ssl_certificate_key /usr/local/nginx/conf/ssl/my.site.key;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
  ssl_ciphers TLS13-AES-256-GCM-SHA384:TLS13-CHACHA20-POLY1305-SHA256:TLS13-AES-128-GCM-SHA256:TLS13-AES-128-CCM-8-SHA256:TLS13-AES-128-CCM-SHA256:EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
  ssl_prefer_server_ciphers on;
  ssl_session_timeout 10m;
  ssl_session_cache builtin:1000 shared:SSL:10m;
  ssl_buffer_size 1400;
  add_header Strict-Transport-Security max-age=15768000;
  ssl_stapling on;
  ssl_stapling_verify on;
  server_name my.site www.my.site;
  access_log off;
  index index.html index.htm index.php;
  root /data/wwwroot/my/public;
  if ($ssl_protocol = "") { return 301 https://$host$request_uri; }
  if ($host != my.site) {  return 301 $scheme://my.site$request_uri;  }
  
  location / {
    try_files $uri @apache;
  }
  location /centrifugo/ {
        rewrite ^/centrifugo/(.*)        /$1 break;
        proxy_pass_header Server;
        proxy_set_header Host $http_host;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_pass http://centrifugo;
    }

    location /centrifugo/connection {
        rewrite ^/centrifugo(.*)        $1 break;

        proxy_next_upstream error;
        gzip on;
        gzip_min_length 1000;
        gzip_proxied any;
        proxy_buffering off;
        keepalive_timeout 65;
        proxy_pass http://centrifugo;
        proxy_read_timeout 60s;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header Host $http_host;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
  location @apache {
    proxy_pass http://127.0.0.1:88;
    include proxy.conf;
  }
  location ~ .*\.(php|php5|cgi|pl)?$ {
    proxy_pass http://127.0.0.1:88;
    include proxy.conf;
  }
  location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|flv|mp4|ico)$ {
    expires 30d;
    access_log off;
  }
  location ~ .*\.(js|css)?$ {
    expires 7d;
    access_log off;
  }
  location ~ /\.ht {
    deny all;
  }
}`
My APP JS
`import Centrifuge from 'centrifuge'
import SockJS from 'sockjs-client'

window.centrifuge = new Centrifuge('https://my.site/connection/sockjs', {
    sockjs: SockJS
});`

AND IN HTML (Blade Laravel)
`<script>
        centrifuge.subscribe("news", function(message) {
            console.log(message);
        });
        centrifuge.connect();
    </script>`

**Comment by chelkaz** [comment]
OMG In documentations talk /connection/websocket
Bat real = /centrifugo/connection/websocket WORK
/centrifugo/connection/jsockjs WORK
Closed) Thx!

**Comment by FZambia** [comment]
If you put Centrifugo on custom Nginx location then of course you have endpoints prefixes with your `location`.
