### ISSUE TITLE
Debug statement in 1.3.0 release

### ISSUE THREAD

**Issue by banks** [centrifugal/centrifuge-js#8]
https://github.com/centrifugal/centrifuge-js/blob/master/centrifuge.js#L715

**Comment by FZambia** [comment]
Ah, rebuilt tag with removed debug line. I have not published 1.3.0 in npm in the morning - did it just now with already fixed code. But I think it's better to make 1.3.1 just to make sure old version not cached somewhere in bower.

**Comment by FZambia** [comment]
Made 1.3.1 quick release - [changelog](https://github.com/centrifugal/centrifuge-js/blob/master/CHANGELOG.md#131)
