### ISSUE TITLE
Private channel token without a extra HTTP request

### ISSUE THREAD

**Issue by Sexual** [centrifugal/centrifuge-js#81]
Is there a way to generate a token without having to have an extra HTTP request to get the private token?

**Comment by FZambia** [comment]
@Sexual hi! It's not possible as it was designed to work in this way. Maybe you don't just need private channel if you don't want to prove subscription with token. Could you describe your use case?

**Comment by FZambia** [comment]
@Sexual please reopen if still actual and you can provide more information.
