### ISSUE TITLE
Cant resubscribe after reconnect

### ISSUE THREAD

**Issue by masterada** [centrifugal/centrifuge-js#83]
## Description

If you subscribe and unsubscribe from a channel, and then a centrifuge reconnect happens, you can no longer subscribe to that channel.

## Steps to reproduce

1. connect centrifuge
2. subscribe to channel 'test': `let sub = centrifuge.subscribe('test', handler)`
3. unsubscribe from channel 'test': `sub.unsubscribe()`
4. reconnect centrifuge (eg: network error)
5. subsribe to channel 'test' again: `let sub = centrifuge.subscribe('test', handler)`

### Expexted:
- centrifuge subscribes to 'test' channel

### Actual:
- centrifuge won't subscribe to 'test' channel

## Other info

Might be related to: https://github.com/centrifugal/centrifuge-js/issues/46

After a bit of investigation, i found out that the subsription is stuck in _STATE_SUBSCRIBING:

1. connect centrifuge
2. subscribe to channel 'test': `let oldSub = centrifuge.subscribe('test', handler)`
3. unsubscribe from channel 'test': `oldSub.unsubscribe()`
4. reconnect centrifuge (eg: network error)
5. check status of oldSub: `console.log(oldSub._status) // prints out 1, expected 4`

**Comment by FZambia** [comment]
@masterada hello, many thanks for detailed description and steps to reproduce, will take a look very soon.

**Comment by FZambia** [comment]
@masterada could you please check library version from dist folder in master branch which already contains fix from f421b6c83ba552fc71e6351b11b1ce8ef7e66828 - I believe it should fix an issue. If it works - will create new release.

**Comment by masterada** [comment]
@FZambia thanks for the quick fix, tested with https://github.com/centrifugal/centrifuge-js/commit/7e859c069582cc58cd6050e8c0136ea597e1f8be, works fine for me.

**Comment by FZambia** [comment]
Thanks! Just released 2.1.6
