### ISSUE TITLE
List Protobuf as an Optional Dependency

### ISSUE THREAD

**Issue by selcouthlyBlue** [centrifugal/centrifuge-js#85]
When installing centrifuge-js using npm, it installs Protobuf as a required dependency. But, what if the one does not intend to use protobuf and decide to stick with the default library? Would it be possible to make Protobuf as an optional dependency?

**Comment by FZambia** [comment]
Hello, protobufjs installed but it should not be included into your final production build due to tree shaking algorithms (at least this works with Webpack). What happens in your case?
