### ISSUE TITLE
Need error hook for any refresh failure

### ISSUE THREAD

**Issue by ernsheong** [centrifugal/centrifuge-js#86]
Referring to https://github.com/centrifugal/centrifuge-js#refreshendpoint

I would like to know when a refresh call has failed, without waiting for `refreshAttempts` to happen, and without relying on `onRefreshFailure`, because once that happens I don't know how to restart the refresh again.

Particularly I use Firebase and often the token has expired, and I need a hook to know when the refresh calls have failed at any time, not just when `refreshAttempts` times has taken place, so that I can force Firebase token refresh and mutate `refreshHeaders` with the new Auth headers (which btw, I kinda hackily replace the `refreshHeader` object directly via `_config` because there is no other way to do so.)

Am I missing some other obvious API? Kindly guide, thanks.

Suggestions:
1. One suggestion is to call `onRefreshFailure` on any failure and pass in the attempts count as the first argument of `onRefreshFailure`... (breaking change)
2. Secondly, expose an API e.g. `setRefreshHeader` to officially replace the `refreshHeaders`, same goes for `subscribeHeaders`

**Comment by FZambia** [comment]
Hello, seems reasonable, but we can't introduce breaking changes. So I suggest adding new callback `onRefreshAttempt` that will be called every time when refresh call succeeded or errored and will include all required context as argument.

And just add setters for headers leaving possibility to set them over config. 

Will this solve your case?

**Comment by ernsheong** [comment]
Thanks. Both `onRefreshAttempt` and setters for headers would be a great addition that solves my case. 👍

**Comment by FZambia** [comment]
OK, you can send pull request to speed up things, otherwise I can do it during this or next weekend. Just let me know if you start working on this.

**Comment by ernsheong** [comment]
I will take a stab at this (and contribute back). Await my PR :)

**Comment by ernsheong** [comment]
@FZambia PTAL, thanks

**Comment by ernsheong** [comment]
I just added setters so I don't have to manually reach into `_config`. Think that will do for now!
