### ISSUE TITLE
Firefox: "SecurityError: The operation is insecure." when sniffing WebSocket support

### ISSUE THREAD

**Issue by ernsheong** [centrifugal/centrifuge-js#87]
Browser Version: Firefox 67.0.3
![image](https://user-images.githubusercontent.com/1343284/59897023-69b5df00-941d-11e9-8163-e5f308af29af.png)

Coming from this line:
![image](https://user-images.githubusercontent.com/1343284/59897042-7b978200-941d-11e9-8467-34b329ed8bac.png)

Something insecure about:

```js
function _websocketSupported() {
  return !(typeof WebSocket !== 'function' && (typeof WebSocket === 'undefined' ? 'undefined' : _typeof(WebSocket)) !== 'object');
}
```

**Comment by FZambia** [comment]
Hello, hmm - I can't reproduce this with Firefox 67.0.4.

Could you make a reproducing example on codepen.io?

**Comment by ernsheong** [comment]
Seems to have disappeared... closing for now.
