### ISSUE TITLE
Subscription `ready()` doesn't appear to work as documented

### ISSUE THREAD

**Issue by banks** [centrifugal/centrifuge-js#9]
The following code works:

```javascript
            var subs = [];
            client.startBatching();
            for (var i = 0; i < HUB_DATA.subs.length; i++) {
                var channel = HUB_DATA.subs[i];
                subs[channel] = client.subscribe(channel, recv);
                subs[channel].on('subscribe', function(ctx) {
                    console.log('Successfully '+(ctx.isResubscribe ? 're' : '')+'subscribed to channel', ctx.channel)
                });
            }
            // Send all subscription messages
            client.stopBatching(true);
```

The `subscribe` call back fires initially and on resubscribe as expected. I'm not yet issuing multiple subscriptions on same page and this all happens before `connect()` so I don't strictly need `ready()` but I wanted to use it anyway.

But if I change the code above to:

```javascript
            ...
                subs[channel].ready(function(ctx) {
                    console.log('Successfully '+(ctx.isResubscribe ? 're' : '')+'subscribed to channel', ctx.channel)
                });
            ...
```

It is never triggered. I tried also providing `errBack` argument and that never fires either.

I've debugged it quickly and it seems To work as expected: `_setSubscribeSuccess` calls to `this._resolve` which executes the `resolve()` callback from promise constructor, but at that point in tracing ES6 promise lib (which is minified in source) jumps around a bit but never results in actually calling my `ready()` handler.

Maybe I'm doing it wrong :)

**Comment by FZambia** [comment]
As we already discussed in gitter - it was a problem of confusing documentation. `ready` is just a helper method needed in rare cases to deal with subscription that was already invoked before (so `subscribe` or `error` events already fired). In most scenarios nobody need to use this method. Already made some  fixes in docs to prevent confusion in future!
