### ISSUE TITLE
Add a destroy method

### ISSUE THREAD

**Issue by scyclops** [centrifugal/centrifuge-js#92]
It would be useful if the client API provided a way to cleanup and destroy a Centrifuge object.

**Comment by FZambia** [comment]
Hello, any insight on how you are planning to use this method? And what it should actually do beyond disconnect and cleaning up internal state?

**Comment by scyclops** [comment]
I think disconnecting and cleaning up internal state is all it should do.

For my use case, only authenticated users need to maintain an active connection to Centrifugo.  So when a user logs out, I need a way to destroy the connection.

**Comment by FZambia** [comment]
Maybe [disconnect](https://github.com/centrifugal/centrifuge-js#disconnect-method) method already does what you need?

**Comment by scyclops** [comment]
I tried using disconnect but it doesn't work when the client is already in a disconnected state because of the disconnected check on this line: https://github.com/centrifugal/centrifuge-js/blob/45eadad8ce2039f94f02be21ac06f4749528c1d8/src/centrifuge.js#L644

For example:
1. User connects to centrifugo
2. User internet stops working (so client is disconnected and is trying to reconnect)
3. User logs out of app (disconnect is called but does nothing because client is already in disconnected state because of 2)
4. User internet starts working again while they are stilled logged out (so client reconnects to centrifugo even though disconnect was called in 3)

I also have a second use case where SockJS is only loaded if the first connection attempt fails.  So I need to destroy and recreate the connection to make it use SockJS for the second connection attempt.

**Comment by FZambia** [comment]
Looks like a bug - manually called disconnect should not result into automatic reconnects even if called in already disconnected state, I will try to reproduce it and write back after that.

**Comment by FZambia** [comment]
#93 should fix this
