### ISSUE TITLE
Question: What Centrifuge::setConnectData actually does?

### ISSUE THREAD

**Issue by cmath10** [centrifugal/centrifuge-js#96]
Hello! I tried to add user information to client (to retrieve it further via subscription::presence, for example), via client.setConnectData({ id: %my-user-id% }), but it seems not working. Probably i misunderstood documentation, and the function used for something else. Could you clarify what the function actually does? I used v1 centrifuge-js previously, old client has the field 'user' in its options. I tried to find something familiar.

**Comment by FZambia** [comment]
@cmath10 hello, in v2 you need to use `sub` field inside JWT token you are passing for authentication. See [documentation](https://centrifugal.github.io/centrifugo/server/authentication/#sub). `setConnectData` not used with Centrifugo server, it's only useful with Centrifuge library at this moment.

**Comment by cmath10** [comment]
> centrifuge.setToken
Yep, i used it. I use phpcent library on my php backend to generate token with function generateConnectionToken - i provide it with userId, then i use generated token on frontend client. If i understood docs well - userId must be present in subscription::presence responce, but none is actually present in responce i receive, so i am not able to identify concrete subscriber

**Comment by FZambia** [comment]
@cmath10 please post a simple reproducing example as gist and then I will try to help you, until that moment I can't guess what's going wrong in your case. if presence does not show anything - make sure client subscribed to a channel that you asking presence for.

**Comment by cmath10** [comment]
@FZambia,

> please post a simple reproducing

https://gist.github.com/cmath10/f35712a47879fc8435fd17ef5da3fc8d

It definitely client subscribed to a channel, cause i can send messages via subscription on both sides and I have 100% successful delivery.

**Comment by FZambia** [comment]
Remove `--client_insecure` option from your docker-compose file, check your JWT over jwt.io site

**Comment by cmath10** [comment]
@FZambia, Option removed, i got token:

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjkiLCJleHAiOjE1NzQ2NjU4ODV9.6YbQPASx0nb1ms7LFkCI81wL3eBfhMENbrvtHweRg8M

I used `--client_insecure` cause on dev environment has no ssl certificate, so my client can't connect due `{ reason: "bad request", reconnect: false }`

> check your JWT over jwt.io site

With HS256 i got 
```json
{
  "sub": "129",
  "exp": 1574665885
}
```

**Comment by FZambia** [comment]
Bad request over WebSocket can't be returned due to certificate issues, In general server logs contain detailed information about bad request reason, I suppose this can be wring secret used. You can write me to Telegram (the same nickname as here) and I will try to help you finding a reason.

**Comment by cmath10** [comment]
This was my mistake - found problem in my code - incorrect es6 destructuring, all steps in gist was correct except fetchToken - in reason of flag --client_insecure was set to true - no token validation was required, then client could authorize with any token or without token at all - which actually happened in my case. No token - no correct presence information :) Thanks @FZambia  for help!
